### ISSUE TITLE
AuditingHistorySearch

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#103]
[Mockup](https://www.figma.com/proto/gC4On1ULcel7UzXMwdS9cY/BAIFAAA?type=design&node-id=257-19005&scaling=scale-down&page-id=46%3A771&starting-point-node-id=46%3A772)

![截圖 2023-06-19 下午1 29 48](https://github.com/CAFECA-IO/boltchain.io/assets/114177573/3ce8d3cd-0c8b-4b42-adf2-a3f999ed4216)

**Comment by Julian0701** [comment]
與 `SearchFilter` 通用

**Comment by Luphia** [comment]
- deprecated mission
