### ISSUE TITLE
[UI] 2.0 Explorer Module規劃 與 主畫面Module製作

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/BAIFA#1090]
根據BAIFA2.0 WF 建立2.0 Explorer Module清單。依據畫面劃分所需Module

**Comment by StrawHo** [comment]
###  Module-Main Page

- [ ] Nav Bar
- [ ] Block Chain List 
- [ ] Language menu 
- [ ] App menu
- [ ] Main page Button Group

**Comment by JodieWu** [comment]
完成時間： 7 hr
https://www.figma.com/design/juscATf1cAwEZWjMCmyz6V/BAIFA-2.0?node-id=1-5&t=RqALx9gdti8T5Xz9-1
