### ISSUE TITLE
[UI] Explorer-Blocks mockup

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/BAIFA#1094]
Explorer-Blocks mockup

**Comment by StrawHo** [comment]
### 製作Mockup頁面內容：

- Chains
- Block
- Block list
- Transactions_List
- Transactions_List(Logout)
- Transaction_Login_Authority
- Transaction_Login_Authority_Mark


LINK:
https://www.figma.com/design/juscATf1cAwEZWjMCmyz6V/BAIFA-2.0?node-id=1-6&t=pvP0mwr7SE0c093I-1

花費時間約 5hr。Done!
