### ISSUE TITLE
[UI] Explorer-Token mockup

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/BAIFA#1095]
Explorer-Token mockup

**Comment by StrawHo** [comment]
### Mockup page

- Token_NFT
- Token_NFT_Inventory
- Token_item_Logout
- Token_item_Login
- Currency_List
- Transactions_List

LINK:
https://www.figma.com/design/juscATf1cAwEZWjMCmyz6V/BAIFA-2.0?node-id=1-6&t=PH5uDyCsqy2BgZvq-1

花費時間4hr20min
