### ISSUE TITLE
[UI] Explorer-Redflag mockup

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/BAIFA#1096]
Explorer-Redflag mockup

**Comment by StrawHo** [comment]
### Mockup page

- Red_flag_Logout
- Red_flag_Login

LINK:
https://www.figma.com/design/juscATf1cAwEZWjMCmyz6V/BAIFA-2.0?node-id=1-6&t=PH5uDyCsqy2BgZvq-1

花費時間約4hr10min
