### ISSUE TITLE
[Design System] Component L-S

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/BAIFA#1103]
- [x] List
- [x] Legend-indicator
- [x] Loading Indicator
- [x] Pagination
- [x] Ratings
- [x] Skeleton

**Comment by StrawHo** [comment]
#### List LINK:
https://www.figma.com/design/hbSbLhdFORx3HQaVpU79qv/BAIFA--Design-System?node-id=2401-3311&t=gu2CJGQfNjZDf9Lv-1

#### Legend-indicator LINK:
https://www.figma.com/design/hbSbLhdFORx3HQaVpU79qv/BAIFA--Design-System?node-id=2402-202&t=gu2CJGQfNjZDf9Lv-1

#### Loading Indicator LINK:
https://www.figma.com/design/hbSbLhdFORx3HQaVpU79qv/BAIFA--Design-System?node-id=2390-38910&t=gu2CJGQfNjZDf9Lv-1
(已附json檔案連結)

#### Pagination LINK:
https://www.figma.com/design/hbSbLhdFORx3HQaVpU79qv/BAIFA--Design-System?node-id=2415-15614&t=gu2CJGQfNjZDf9Lv-1
**prototype:**https://www.figma.com/proto/hbSbLhdFORx3HQaVpU79qv/BAIFA-Design-System?node-id=2415-15614&viewport=281%2C436%2C0.5&t=gu2CJGQfNjZDf9Lv-0&scaling=min-zoom&starting-point-node-id=2415%3A15614

#### Ratings LINK:
https://www.figma.com/design/hbSbLhdFORx3HQaVpU79qv/BAIFA--Design-System?node-id=2439-16366&t=gu2CJGQfNjZDf9Lv-1
**prototype:**https://www.figma.com/proto/hbSbLhdFORx3HQaVpU79qv/BAIFA-Design-System?node-id=2439-16366&viewport=395%2C295%2C0.5&t=gu2CJGQfNjZDf9Lv-0&scaling=min-zoom&starting-point-node-id=2439%3A16366

#### Skeleton LINK:
https://www.figma.com/design/hbSbLhdFORx3HQaVpU79qv/BAIFA--Design-System?node-id=2390-38916&t=gu2CJGQfNjZDf9Lv-1

**Comment by StrawHo** [comment]
花費時間約 6hr 50 min 

Done!
