### ISSUE TITLE
[Module] List

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/BAIFA#1112]
- [x] Address Table
- [x] Address Table card
- [x] Contracts List Table
- [x] Contracts Table card
- [x] Token List Table
- [x] Token Table card
- [x] Transactions List Table
- [x] Transactions Table card
- [x] Currency List Table
- [x] Currency Table card
- [x] Red Flags List Table
- [x] Red Flags Table card
- [x] Black List Table
- [x] Black List Table card

**Comment by JodieWu** [comment]
完成時間：7 hr

https://www.figma.com/design/juscATf1cAwEZWjMCmyz6V/BAIFA-2.0?node-id=1-5&t=DKX1dAMY5pq6Nzra-1
