### ISSUE TITLE
[Module] Token

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/BAIFA#1114]
- [x] Profile Card
- [x] Profile List
- [x] Top100 holder table
- [x] Top100 card
- [x] Inventory card
- [x] Profile Photo (Logout)
- [x] Profile List
- [x] Profile Photo (Login)
- [x] Coin page -Coin Card
- [x] Coin page-Profile List
- [x] Coin page-Preview KYT module
- [x] Red flag page-Profile Card
- [x] Red flag page--Profile List

**Comment by JodieWu** [comment]
完成時間： 8 hr

https://www.figma.com/design/juscATf1cAwEZWjMCmyz6V/BAIFA-2.0?node-id=1-5&t=IbclAx0NG2rMBoj3-1
