### ISSUE TITLE
[UX] Token Mobile

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/BAIFA#1129]
Token 手機版設計

**Comment by StrawHo** [comment]
06/28
Token Module:
https://www.figma.com/design/juscATf1cAwEZWjMCmyz6V/BAIFA-2.0?node-id=1-5&t=NWGGvxM2etVeIniW-1

目前花費時間0.5hr。還需要4~5hr

**Comment by StrawHo** [comment]
07/01
製作Mob page:
Token_item_Logout&Login
Token_NFT
Token_NFT_Inventory
Coin

LINK:
https://www.figma.com/design/juscATf1cAwEZWjMCmyz6V/BAIFA-2.0?node-id=291-312380&t=mFpnlzyRFoViuWte-1

總共花費時間為：4hr
