### ISSUE TITLE
[UX] Red flag & black list mobile

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/BAIFA#1130]
Red flag & black list 手機版設計

**Comment by StrawHo** [comment]
完成項目包含
Blacklist,Red flag,Red flag log out

LINK:
https://www.figma.com/design/juscATf1cAwEZWjMCmyz6V/BAIFA-2.0?node-id=291-312380&t=NWGGvxM2etVeIniW-1

花費時間約3hr50min，Done!
