### ISSUE TITLE
[UX] Setting Mobile

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/BAIFA#1131]
Setting 手機版設計

**Comment by StrawHo** [comment]
- [ ] Login page
- [ ] Setting list
- [ ] general setting
- [ ] Subscription
- [ ] Payment & Billing

**Comment by StrawHo** [comment]
07/01已完成 Login page,Setting list,Payment & Billing
剩餘general setting、Subscription

LINK:
https://www.figma.com/design/juscATf1cAwEZWjMCmyz6V/BAIFA-2.0?node-id=291-312380&t=mFpnlzyRFoViuWte-1
目前花費時間為3hr 45min 預計還需4~5hr
