### ISSUE TITLE
ReviewPageBody

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#115]
[Mockup](https://www.figma.com/proto/gC4On1ULcel7UzXMwdS9cY/BAIFAAA?type=design&node-id=307-27613&scaling=scale-down&page-id=46%3A771&starting-point-node-id=46%3A772)

- Title(Reviews [AddressId])
- 評分 (~ of 5)

**Comment by Luphia** [comment]
- deprecated mission
