### ISSUE TITLE
currency icon 圖片命名修改

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/BAIFA#1155]
看要不要改成
固定為 chain id + currency 的 address

- [x] #1157
- [x] #1158

**Comment by godmmt** [comment]
8017_0x0000000000000000000000000000000000000000.svg

但如果要用 address
要修改 API 可以回傳 address

ICurrencyDetailString 也要修改

API 文件也被要修改

**Comment by Luphia** [comment]
改吧，交給你了

**Comment by godmmt** [comment]
0710: took 1 hour

done.
