### ISSUE TITLE
確認BAIFA撈到的資料是否能產生報表

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/BAIFA#152]
- [API Doc](https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.0.0)
- [related issue - baifa crawler 根據需求新增功能 #157](https://github.com/CAFECA-IO/tbd-backend/issues/157)
- [Excel](https://docs.google.com/spreadsheets/d/17jDjXwsnMePKH2kKP06E2vGGMnj3MTseT_OaES7P8Hg/edit#gid=1534487383)｜ [Excel v1](https://docs.google.com/spreadsheets/d/1Dm3GMikIMrU9Fv5TeIgjwtN9oIpK43Tw5dzdEZ-C9Ow/edit#gid=0)
- 紀錄修改資產負債表的API需求 [#182](https://github.com/CAFECA-IO/BAIFA/issues/182)

**Comment by arealclimber** [comment]
taking 1 hrs
remaining 3 hrs

**Comment by arealclimber** [comment]
taking 7 hrs (1 hrs 跟 Jodie 對財報，6 hrs 檢視 API 資料跟財報)
remaining 4 hrs
-----
- **對於資產，總額＝各幣種的數量x出財報當下的匯率**
- [ ]  Balance sheet
    - [ ]  這次結算時，我們自己的USDT，幣種數量跟總額
    - [ ]  這次結算時，我們自己的USDC，幣種數量跟總額
    - [ ]  這次結算時，我們自己的BTC，幣種數量跟總額
    - [ ]  這次結算時，我們自己的ETH，幣種數量跟總額
    - [ ]  這次結算時，用戶有多少USDT留在我們平台上，幣種數量跟總額
    - [ ]  這次結算時，用戶有多少USDC留在我們平台上，幣種數量跟總額
    - [ ]  這次結算時，用戶有多少BTC留在我們平台上，幣種數量跟總額
    - [ ]  這次結算時，用戶有多少ETH留在我們平台上，幣種數量跟總額
    - [ ]  這次結算時，我們還沒跟用戶收的費用總額（也就是用戶還沒關倉的那些CFD的對應費用）
    - [ ]  這次結算時，我們還沒給交易所的費用總額（也就是我們在其他交易所還沒關倉的那些CFD的對應費用）
    - [ ]  這次結算時，用戶在我們平台上還沒關倉的ＣＦＤ的保證金總額
    - [ ]  這次結算時，我們自己資產當下的價值－資產成本總額的差額
    - [ ]  上次結算到這次結算期間，我們賺到的錢總額（各幣種的數量x出財報當下的匯率）

---

- **對於收入，總額＝該幣數量x各交易發生當下的匯率**
- [ ]  Income statement
    - [ ]  上次結算到這次結算期間，我們賺到的錢的總額（各幣種的數量x每筆交易發生當下的匯率）
    - [ ]  上次結算到這次結算期間，我們付出的成本：給礦工的gas fee、給其他交易所的費用總額
    - [ ]  上次結算到這次結算期間，我們給儲戶的利息總額
    - [ ]  這次結算時，我們自己資產當下的價值－資產成本總額的差額

**Comment by arealclimber** [comment]
## 7/27 更新:

- **對於資產，總額＝各幣種的數量x出財報當下的匯率**
- [ ]  Balance sheet
    - [ ]  這次結算時，我們自己的資產，幣種數量跟總額跟百分比；需要成本價（取得資產時的匯率）跟現在價值（出財報當下的匯率）
        - [ ]  USDT
        - [ ]  BTC
        - [ ]  ETH
    - [ ]  這次結算時，用戶留在我們平台上的資產，幣種數量跟總額跟百分比（出財報當下的匯率）
        - [ ]  USDT
        - [ ]  BTC
        - [ ]  ETH
    - [ ]  這次結算時，用戶在我們平台上還沒關倉的CFD的保證金，幣種數量跟總額（出財報當下的匯率）
        - [ ]  USDT
        - [ ]  BTC
        - [ ]  ETH
    - [ ]  這次結算時，我們還沒跟用戶收的費用總額（也就是用戶還沒關倉的那些CFD的對應費用）
    - [ ]  這次結算時，我們還沒給交易所的費用總額（也就是我們在其他交易所還沒關倉的那些CFD的對應費用）
    - [ ]  這次結算時，我們自己資產當下的價值－資產成本總額的差額
    - [ ]  這次結算時，我們賺到的錢總額（各幣種的數量x出財報當下的匯率）
    - [ ]  上次結算到這次結算期間，我們賺到的錢的總額（各幣種的數量x每筆交易發生當下的匯率）`spreadFees`+`stopFees`+`closeFees`
    - [ ]  出財報當下用的匯率、上期出財報時用的匯率

---

- **對於收入，總額＝該幣數量x各交易發生當下的匯率**
- [ ]  Statements of Comprehensive income
    - [ ]  上次結算到這次結算期間，我們付出的成本：給礦工的gas fee、給其他交易所的費用總額
    - [ ]  上次結算到這次結算期間，我們給儲戶的利息總額
    - [ ]  這次結算時，我們自己資產當下的價值－資產成本總額的差額
- [ ]  Statements of Cash Flow
    - [ ]  上次結算到這次結算期間，我們賺到的錢的幣種數量、總額
        - [ ]  USDT
        - [ ]  BTC
        - [ ]  ETH
    - [ ]  上次結算到這次結算期間，我們用USDT、USDC、法幣買加密貨幣的總額
    - [ ]  上次結算到這次結算期間，用戶入金幣種數量跟總額 `deposits`.`totalDepositsAmount`
    - [ ]  上次結算到這次結算期間，用戶出金幣種數量跟總額 `withdraws`.`totalWithdrawsAmount`
- [ ]  須通報的可疑交易，區分為自身行為以及與第三方有關行為細項，並統計個別項目的數量
    - [ ]  自身行為
        1. Multiple Transfers
        2. Frequent Large Transfers
        3. Large Withdrawals
        4. Large Deposits
        5. Multiple Withdrawals
        6. Multiple Deposits
        7. High-Risk IP Addresses？
    - [ ]  與第三方有關行為
        1. Connections with Coin Mixers
        2. Involvement with the Dark Web
        3. Transactions with Blacklisted Entities
        4. Involvement with Gambling Websites
        5. Involvement with the Dark Web
- [ ]  上述資料都需要上上次結算到上次結算期間，以產生上個月的資料作為對照；也需要去年這段期間的資料（例如這期要出的是今年七月底的報表，那還需要去年六月底到七月底的資料），以產生資料作為對照
- [ ]  我們金庫的地址跟金庫活躍的起始時間

**Comment by arealclimber** [comment]
## [8/22 更新:](https://www.notion.so/soul-quenching/shared-dea83ef6f1574ef09f4eab437bcb23e4?pvs=4#d57e13619929492f8bf083da3b31086d)

- [ ]  Balance sheet
    - [ ]  指定時間點的狀態，平台上的 USDT 總額，包括我們自己的跟用戶的
    - [ ]  指定時間點的狀態，我們自己應該收到卻還沒收到的錢
    - [ ]  指定時間點的狀態，平台上的加密貨幣總額，包括我們自己的跟用戶的
    - [ ]  指定時間點的狀態，用戶放在平台上的資產總額
    - [ ]  指定時間點的狀態，我們自己應該給別人卻還沒給的錢
    - [ ]  指定時間點的狀態，我們自己放在平台上的資產總額
    - [ ]  指定時間點的狀態，我們賺到的且還沒分給股東的總額

**Comment by TzuHanLiang** [comment]
以[ BAIFA#182](https://github.com/CAFECA-IO/BAIFA/issues/182) 為主
