### ISSUE TITLE
修改損益表的API需求

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/BAIFA#184]
### 加密貨幣交易所損益表 (Cryptocurrency Exchange Income Statement)

**收入 (Revenues)：**
- 交易手續費收入 (Transaction Fee Income)：500,000元
- 客戶入金 (Customer Deposits)：10,000,000元
- 客戶出金 (Customer Withdrawals)：-8,000,000元
- 交易收入 (Trading Income)：300,000元

**費用 (Expenses)：**
- 交易費用 (Trading Expenses)：100,000元
- 營運費用 (Operating Expenses)：300,000元
- 折舊及攤銷 (Depreciation & Amortization)：50,000元
- 利息費用 (Interest Expense)：50,000元

**淨利 (Net Income)：** 50,000元

**Comment by TzuHanLiang** [comment]
- 參考: [製作加密貨幣交易所的損益表的完整指南](https://github.com/CAFECA-IO/KnowledgeManagement/blob/master/TideBit-DeFi/crypto_exchange_p&l_guide.md)

**Comment by arealclimber** [comment]
> * 參考: [製作加密貨幣交易所的損益表的完整指南](https://github.com/CAFECA-IO/KnowledgeManagement/blob/master/TideBit-DeFi/crypto_exchange_p&l_guide.md)
> 
> 公司名稱 (Company Name) 綜合損益表 (Comprehensive Income Statement) 從 YYYY-MM-01 到 YYYY-MM-DD (From YYYY-MM-01 to YYYY-MM-DD)
> 
> 1. 收入部分:
> 
> * 總收入 (Total Income): [美金]
> * 細節:
>   
>   * 交易手續費 (Transaction Fee):
>     
>     * 交易手續費總額 (Total Transaction Fee in USD): [美金]
>     * 細節:
>       
>       * BTC:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>       * ETH:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>       * USD: [金額]
>       * USDT:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>       * [其他幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>   * 點差費 (Spread Fee):
>     
>     * 點差費總額 (Total Spread Fee in USD): [美金]
>     * 細節:
>       
>       * [幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>   * 保證停損手續費 (Guaranteed Stop Loss Fee):
>     
>     * 保證停損手續費總額 (Total GSL Fee in USD): [美金]
>     * 細節:
>       
>       * [幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>   * 強制平倉費 (Liquidation Fee):
>     
>     * 強制平倉費總額 (Total Liquidation Fee in USD): [美金]
>     * 細節:
>       
>       * [幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>   * 提現手續費 (Withdrawal Fee):
>     
>     * 提現手續費總額 (Total Withdrawal Fee in USD): [美金]
>     * 細節:
>       
>       * [幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>   * 入金手續費 (Deposit Fee):
>     
>     * 入金手續費總額 (Total Deposit Fee in USD): [美金]
>     * 細節:
>       
>       * [幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>   * 其他收入 (Other Income):
>     
>     * 其他收入總額 (Total Other Income in USD): [美金]
>     * 細節:
>       
>       * [幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
> 
> 2. 成本部分:
> 
> * 總成本 (Total Costs): [美金]
> * 細節:
>   
>   * 技術供應商費用 (Technical Provider Fee): [美金]
>   * 市場數據供應商費用 (Market Data Provider Fee): [美金]
>   * 新幣上架成本 (New Coin Listing Cost): [美金]
> 
> 3. 營業費用部分:
> 
> * 總營業費用 (Total Operating Expenses): [美金]
> * 細節:
>   
>   * 員工薪資 (Salaries): [美金]
>   * 租金 (Rent): [美金]
>   * 市場推廣 (Marketing): [美金]
>   * 返傭費用 (Commission Rebates):
>     
>     * 返傭費用總額 (Total Commission Rebates in USD): [美金]
>     * 細節:
>       
>       * [幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
> 
> 4. 金融費用部分 (Financial Costs):
> 
> * 總金融費用 (Total Financial Costs): [美金]
> * 細節:
>   
>   * 支付的利息 (Interest Expense): [美金]
>   * 加密貨幣外匯損益 (Cryptocurrency Forex Gains/Losses):
>   * 法幣換加密貨幣損失 (Fiat to Cryptocurrency Conversion Losses): [美金]
>   * 加密貨幣換法幣損失 (Cryptocurrency to Fiat Conversion Losses): [美金]
>   * 法幣互換損失 (Fiat to Fiat Conversion Losses): [美金]
> 
> 4. 其他損益部分:
> 
> * 總其他損益 (Total Other Gains/Losses): [美金]
> * 細節:
>   
>   * 投資損益 (Investment Gains/Losses): [美金]
>   * 外匯損益 (Forex Gains/Losses): [美金]
>   * 加密貨幣損益 (Cryptocurrency Gains/Losses): [美金]
>     
>     * 加密貨幣損益總額 (Total Cryptocurrency Gains/Losses in USD): [美金]
>     * 細節:
>       
>       * [幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
> 
> 5. 淨利潤 (Net Profit or Loss): [美金]
> 
> 簽署 (Signed): 日期 (Date):

以下先依照上述資料產生對應的 json 格式，還未進行細節確認

```json

{
  "success": true,
  "code": "00000000",
  "reason": "ERROR_MESSAGE.SUCCESS",
  "data": {
  "companyName": "加密貨幣交易所A",
  "comprehensiveIncomeStatement": {
    "dateFrom": "2023-01-01",
    "dateTo": "2023-12-31",
    "income": {
      "totalIncome": 12000000,
      "details": {
        "transactionFee": {
          "totalTransactionFeeInUSD": 2000000,
          "breakdown": {
            "BTC": {
              "quantity": 15,
              "valueInUSD": 675000
            },
            "ETH": {
              "quantity": 30,
              "valueInUSD": 450000
            },
            "USD": 500000,
            "USDT": {
              "quantity": 100000,
              "valueInUSD": 100000
            },
            "OTHER": {
              "quantity": 1000,
              "valueInUSD": 30000
            }
          }
        },
        "spreadFee": {
          "totalSpreadFeeInUSD": 1500000,
          "breakdown": {
            "BTC": {
              "quantity": 10,
              "valueInUSD": 450000
            }
          }
        },
        //...其他收入詳情
      }
    },
    "costs": {
      "totalCosts": 2000000,
      "details": {
        "technicalProviderFee": 500000,
        "marketDataProviderFee": 400000,
        "newCoinListingCost": 300000
      }
    },
    "operatingExpenses": {
      "totalOperatingExpenses": 3000000,
      "details": {
        "salaries": 1000000,
        "rent": 500000,
        "marketing": 400000,
        "commissionRebates": {
          "totalCommissionRebatesInUSD": 300000,
          "breakdown": {
            "BTC": {
              "quantity": 5,
              "valueInUSD": 225000
            }
          }
        }
      }
    },
    "financialCosts": {
      "totalFinancialCosts": 1000000,
      "details": {
        "interestExpense": 300000,
        "cryptocurrencyForexGainsLosses": 200000,
        "fiatToCryptocurrencyConversionLosses": 250000,
        "cryptocurrencyToFiatConversionLosses": 150000,
        "fiatToFiatConversionLosses": 100000
      }
    },
    "otherGainsLosses": {
      "totalOtherGainsLosses": 500000,
      "details": {
        "investmentGainsLosses": 200000,
        "forexGainsLosses": 100000,
        "cryptocurrencyGainsLosses": {
          "totalCryptocurrencyGainsLossesInUSD": 200000,
          "breakdown": {
            "BTC": {
              "quantity": 3,
              "valueInUSD": 135000
            }
          }
        }
      }
    },
    "netProfitOrLoss": 2500000
  }
}

}



```

**Comment by arealclimber** [comment]
```json

{
  "success": true,
  "code": "00000000",
  "reason": "ERROR_MESSAGE.SUCCESS",
  "data": {
    "id": "comprehensive_income_statement-123456_78910",
    "date": "2023-09-04T16:00:00.000Z",
    "income": {
      "totalIncome": 12000000,
      "details": {
        "transactionFee": {
          "totalTransactionFeeInUSD": 2000000,
          "breakdown": {
            "BTC": {
              "quantity": 15,
              "valueInUSD": 675000
            },
            "ETH": {
              "quantity": 30,
              "valueInUSD": 450000
            },
            "USD": 500000,
            "USDT": {
              "quantity": 100000,
              "valueInUSD": 100000
            }
            //...其他幣種詳情
          }
        },
        "spreadFee": {
          "totalSpreadFeeInUSD": 450000,
          "breakdown": {
            "BTC": {
              "quantity": 10,
              "valueInUSD": 450000
            }
          }
        }
        //...其他收入詳情
      }
    },
    "costs": {
      "totalCosts": 1200000,
      "details": {
        "technicalProviderFee": 500000,
        "marketDataProviderFee": 400000,
        "newCoinListingCost": 300000
      }
    },
    "operatingExpenses": {
      "totalOperatingExpenses": 2225000,
      "details": {
        "salaries": 1000000,
        "rent": 500000,
        "marketing": 400000,
        "commissionRebates": {
          "totalCommissionRebatesInUSD": 325000,
          "breakdown": {
            "BTC": {
              "quantity": 5,
              "valueInUSD": 225000
            },
            "USDC": {
              "quantity": 100000,
              "valueInUSD": 100000
            }
          }
        }
      }
    },
    "financialCosts": {
      "totalFinancialCosts": 1000000,
      "details": {
        "interestExpense": 300000,
        "cryptocurrencyForexGains": 200000, // Cryptocurrency Forex Gains/Losses
        "fiatToCryptocurrencyConversionLosses": 250000,
        "cryptocurrencyToFiatConversionLosses": 150000,
        "fiatToFiatConversionLosses": 100000
      }
    },
    "otherGains": {
      "totalOtherGains": 435000, // Total Other Gains/Losses
      "details": {
        "investmentGains": 200000,
        "forexGains": 100000, // Forex Gains/Losses
        "cryptocurrencyGains": {
          // Cryptocurrency Gains/Losses
          "totalCryptocurrencyGainsInUSD": 135000,
          "breakdown": {
            "BTC": {
              "quantity": 3,
              "valueInUSD": 135000
            }
          }
        }
      }
    },
    "netProfit": 2500000 // Net Profit or Loss
  }
}

```

**Comment by TzuHanLiang** [comment]
> 延續 API v1.0.1 格式，並依照報表呈現需求，整理 API 回傳資料範例，請 @TzuHanLiang 提出需要調整的部分
> 
> ```json
> {
>   "success": true,
>   "code": "00000000",
>   "reason": "ERROR_MESSAGE.SUCCESS",
>   "data": {
>     "id": "comprehensive_income_statement-123456_78910",
>     "date": "2023-09-04T16:00:00.000Z",
>     "income": {
>       "totalIncome": 12000000,
>       "details": {
>         "transactionFee": {
>           "totalTransactionFeeInUSD": 2000000,
>           "breakdown": {
>             "BTC": {
>               "quantity": 15,
>               "valueInUSD": 675000
>             },
>             "ETH": {
>               "quantity": 30,
>               "valueInUSD": 450000
>             },
>             "USD": 500000,
>             "USDT": {
>               "quantity": 100000,
>               "valueInUSD": 100000
>             }
>             //...其他幣種詳情
>           }
>         },
>         "spreadFee": {
>           "totalSpreadFeeInUSD": 450000,
>           "breakdown": {
>             "BTC": {
>               "quantity": 10,
>               "valueInUSD": 450000
>             }
>           }
>         }
>         //...其他收入詳情
>       }
>     },
>     "costs": {
>       "totalCosts": 1200000,
>       "details": {
>         "technicalProviderFee": 500000,
>         "marketDataProviderFee": 400000,
>         "newCoinListingCost": 300000
>       }
>     },
>     "operatingExpenses": {
>       "totalOperatingExpenses": 2225000,
>       "details": {
>         "salaries": 1000000,
>         "rent": 500000,
>         "marketing": 400000,
>         "commissionRebates": {
>           "totalCommissionRebatesInUSD": 325000,
>           "breakdown": {
>             "BTC": {
>               "quantity": 5,
>               "valueInUSD": 225000
>             },
>             "USDC": {
>               "quantity": 100000,
>               "valueInUSD": 100000
>             }
>           }
>         }
>       }
>     },
>     "financialCosts": {
>       "totalFinancialCosts": 1000000,
>       "details": {
>         "interestExpense": 300000,
>         "cryptocurrencyForexLosses": 200000, // Cryptocurrency Forex Gains/Losses
>         "fiatToCryptocurrencyConversionLosses": 250000,
>         "cryptocurrencyToFiatConversionLosses": 150000,
>         "fiatToFiatConversionLosses": 100000
>       }
>     },
>     "otherGains": {
>       "totalOtherGains": 435000, // Total Other Gains/Losses
>       "details": {
>         "investmentGains": 200000,
>         "forexGains": 100000, // Forex Gains/Losses
>         "cryptocurrencyGains": {
>           // Cryptocurrency Gains/Losses
>           "totalCryptocurrencyGainsInUSD": 135000,
>           "breakdown": {
>             "BTC": {
>               "quantity": 3,
>               "valueInUSD": 135000
>             }
>           }
>         }
>       }
>     },
>     "netProfit": 2500000 // Net Profit or Loss
>   }
> }
> ```

我認為這個版本OK， 明天開始實作，若實作中遇到問題再提出與 @arealclimber  討論

**Comment by TzuHanLiang** [comment]
@arealclimber 因為之前定義過 
```typescript
// 每種貨幣的詳細數據
export interface CurrencyDetail {
  type: ICurrencyType; // 貨幣類型
  amount: number; // 該貨幣的數量
  fairValue: number; // 該貨幣的公允價值
  costValue: number; // 該貨幣的成本價值
}
```
並且在 balance sheet 及 cash flow 都有使用，我覺得 breakdown 裡面的各貨幣細節也可以用這個格式，amount 對於 quantity，fairValue 對應 valueInUSD。

**Comment by arealclimber** [comment]
> @arealclimber 因為之前定義過
> 
> ```ts
> // 每種貨幣的詳細數據
> export interface CurrencyDetail {
>   type: ICurrencyType; // 貨幣類型
>   amount: number; // 該貨幣的數量
>   fairValue: number; // 該貨幣的公允價值
>   costValue: number; // 該貨幣的成本價值
> }
> ```
> 
> 並且在 balance sheet 及 cash flow 都有使用，我覺得 breakdown 裡面的各貨幣細節也可以用這個格式，amount 對應 quantity，fairValue 對應 valueInUSD。

同意

**Comment by arealclimber** [comment]
以下為 API 資料與財報的對照，目前 API 的 `income.details.otherIncome` 沒有在財報上顯示，想問 @TzuHanLiang 這邊的 otherIncome 是什麼? 

![image](https://github.com/CAFECA-IO/BAIFA/assets/20677913/67a7e5de-988b-4b73-b7b0-467471892020)

**Comment by TzuHanLiang** [comment]
這是我前面損益表裡面列出來的收入
<img width="914" alt="Screenshot 2023-09-06 at 2 04 40 PM" src="https://github.com/CAFECA-IO/BAIFA/assets/17249354/f1641248-3ff5-40c8-b133-c60fb58a977e">


> * 參考: [製作加密貨幣交易所的損益表的完整指南](https://github.com/CAFECA-IO/KnowledgeManagement/blob/master/TideBit-DeFi/crypto_exchange_p&l_guide.md)
> 
> 公司名稱 (Company Name) 綜合損益表 (Comprehensive Income Statement) 從 YYYY-MM-01 到 YYYY-MM-DD (From YYYY-MM-01 to YYYY-MM-DD)
> 
> 1. 收入部分:
> 
> * 總收入 (Total Income): [美金]
> * 細節:
>   
>   * 交易手續費 (Transaction Fee):
>     
>     * 交易手續費總額 (Total Transaction Fee in USD): [美金]
>     * 細節:
>       
>       * BTC:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>       * ETH:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>       * USD: [金額]
>       * USDT:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>       * [其他幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>   * 點差費 (Spread Fee):
>     
>     * 點差費總額 (Total Spread Fee in USD): [美金]
>     * 細節:
>       
>       * [幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>   * 保證停損手續費 (Guaranteed Stop Loss Fee):
>     
>     * 保證停損手續費總額 (Total GSL Fee in USD): [美金]
>     * 細節:
>       
>       * [幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>   * 強制平倉費 (Liquidation Fee):
>     
>     * 強制平倉費總額 (Total Liquidation Fee in USD): [美金]
>     * 細節:
>       
>       * [幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>   * 提現手續費 (Withdrawal Fee):
>     
>     * 提現手續費總額 (Total Withdrawal Fee in USD): [美金]
>     * 細節:
>       
>       * [幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>   * 入金手續費 (Deposit Fee):
>     
>     * 入金手續費總額 (Total Deposit Fee in USD): [美金]
>     * 細節:
>       
>       * [幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
>   * 其他收入 (Other Income):
>     
>     * 其他收入總額 (Total Other Income in USD): [美金]
>     * 細節:
>       
>       * [幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
> 
> 2. 成本部分:
> 
> * 總成本 (Total Costs): [美金]
> * 細節:
>   
>   * 技術供應商費用 (Technical Provider Fee): [美金]
>   * 市場數據供應商費用 (Market Data Provider Fee): [美金]
>   * 新幣上架成本 (New Coin Listing Cost): [美金]
> 
> 3. 營業費用部分:
> 
> * 總營業費用 (Total Operating Expenses): [美金]
> * 細節:
>   
>   * 員工薪資 (Salaries): [美金]
>   * 租金 (Rent): [美金]
>   * 市場推廣 (Marketing): [美金]
>   * 返傭費用 (Commission Rebates):
>     
>     * 返傭費用總額 (Total Commission Rebates in USD): [美金]
>     * 細節:
>       
>       * [幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
> 
> 4. 金融費用部分 (Financial Costs):
> 
> * 總金融費用 (Total Financial Costs): [美金]
> * 細節:
>   
>   * 支付的利息 (Interest Expense): [美金]
>   * 加密貨幣外匯損益 (Cryptocurrency Forex Gains/Losses):
>   * 法幣換加密貨幣損失 (Fiat to Cryptocurrency Conversion Losses): [美金]
>   * 加密貨幣換法幣損失 (Cryptocurrency to Fiat Conversion Losses): [美金]
>   * 法幣互換損失 (Fiat to Fiat Conversion Losses): [美金]
> 
> 4. 其他損益部分:
> 
> * 總其他損益 (Total Other Gains/Losses): [美金]
> * 細節:
>   
>   * 投資損益 (Investment Gains/Losses): [美金]
>   * 外匯損益 (Forex Gains/Losses): [美金]
>   * 加密貨幣損益 (Cryptocurrency Gains/Losses): [美金]
>     
>     * 加密貨幣損益總額 (Total Cryptocurrency Gains/Losses in USD): [美金]
>     * 細節:
>       
>       * [幣種]:
>         
>         * 數量: [數量]
>         * 成本價值/持有價值: [美金]
> 
> 5. 淨利潤 (Net Profit or Loss): [美金]
> 
> 簽署 (Signed): 日期 (Date):

這是我前面損益表裡面列出來的收入，還有一個 spreadFee API 裡面有提供但是你的excel 沒有，spreadFee應該要在 excel 補上，otherIncome 可以移除
<img width="914" alt="Screenshot 2023-09-06 at 2 04 40 PM" src="https://github.com/CAFECA-IO/BAIFA/assets/17249354/f1641248-3ff5-40c8-b133-c60fb58a977e">

**Comment by arealclimber** [comment]
> > * 參考: [製作加密貨幣交易所的損益表的完整指南](https://github.com/CAFECA-IO/KnowledgeManagement/blob/master/TideBit-DeFi/crypto_exchange_p&l_guide.md)
> > 
> > 公司名稱 (Company Name) 綜合損益表 (Comprehensive Income Statement) 從 YYYY-MM-01 到 YYYY-MM-DD (From YYYY-MM-01 to YYYY-MM-DD)
> > 
> > 1. 收入部分:
> > 
> > 
> > * 總收入 (Total Income): [美金]
> > * 細節:
> >   
> >   * 交易手續費 (Transaction Fee):
> >     
> >     * 交易手續費總額 (Total Transaction Fee in USD): [美金]
> >     * 細節:
> >       
> >       * BTC:
> >         
> >         * 數量: [數量]
> >         * 成本價值/持有價值: [美金]
> >       * ETH:
> >         
> >         * 數量: [數量]
> >         * 成本價值/持有價值: [美金]
> >       * USD: [金額]
> >       * USDT:
> >         
> >         * 數量: [數量]
> >         * 成本價值/持有價值: [美金]
> >       * [其他幣種]:
> >         
> >         * 數量: [數量]
> >         * 成本價值/持有價值: [美金]
> >   * 點差費 (Spread Fee):
> >     
> >     * 點差費總額 (Total Spread Fee in USD): [美金]
> >     * 細節:
> >       
> >       * [幣種]:
> >         
> >         * 數量: [數量]
> >         * 成本價值/持有價值: [美金]
> >   * 保證停損手續費 (Guaranteed Stop Loss Fee):
> >     
> >     * 保證停損手續費總額 (Total GSL Fee in USD): [美金]
> >     * 細節:
> >       
> >       * [幣種]:
> >         
> >         * 數量: [數量]
> >         * 成本價值/持有價值: [美金]
> >   * 強制平倉費 (Liquidation Fee):
> >     
> >     * 強制平倉費總額 (Total Liquidation Fee in USD): [美金]
> >     * 細節:
> >       
> >       * [幣種]:
> >         
> >         * 數量: [數量]
> >         * 成本價值/持有價值: [美金]
> >   * 提現手續費 (Withdrawal Fee):
> >     
> >     * 提現手續費總額 (Total Withdrawal Fee in USD): [美金]
> >     * 細節:
> >       
> >       * [幣種]:
> >         
> >         * 數量: [數量]
> >         * 成本價值/持有價值: [美金]
> >   * 入金手續費 (Deposit Fee):
> >     
> >     * 入金手續費總額 (Total Deposit Fee in USD): [美金]
> >     * 細節:
> >       
> >       * [幣種]:
> >         
> >         * 數量: [數量]
> >         * 成本價值/持有價值: [美金]
> >   * 其他收入 (Other Income):
> >     
> >     * 其他收入總額 (Total Other Income in USD): [美金]
> >     * 細節:
> >       
> >       * [幣種]:
> >         
> >         * 數量: [數量]
> >         * 成本價值/持有價值: [美金]
> > 
> > 
> > 2. 成本部分:
> > 
> > 
> > * 總成本 (Total Costs): [美金]
> > * 細節:
> >   
> >   * 技術供應商費用 (Technical Provider Fee): [美金]
> >   * 市場數據供應商費用 (Market Data Provider Fee): [美金]
> >   * 新幣上架成本 (New Coin Listing Cost): [美金]
> > 
> > 
> > 3. 營業費用部分:
> > 
> > 
> > * 總營業費用 (Total Operating Expenses): [美金]
> > * 細節:
> >   
> >   * 員工薪資 (Salaries): [美金]
> >   * 租金 (Rent): [美金]
> >   * 市場推廣 (Marketing): [美金]
> >   * 返傭費用 (Commission Rebates):
> >     
> >     * 返傭費用總額 (Total Commission Rebates in USD): [美金]
> >     * 細節:
> >       
> >       * [幣種]:
> >         
> >         * 數量: [數量]
> >         * 成本價值/持有價值: [美金]
> > 
> > 
> > 4. 金融費用部分 (Financial Costs):
> > 
> > 
> > * 總金融費用 (Total Financial Costs): [美金]
> > * 細節:
> >   
> >   * 支付的利息 (Interest Expense): [美金]
> >   * 加密貨幣外匯損益 (Cryptocurrency Forex Gains/Losses):
> >   * 法幣換加密貨幣損失 (Fiat to Cryptocurrency Conversion Losses): [美金]
> >   * 加密貨幣換法幣損失 (Cryptocurrency to Fiat Conversion Losses): [美金]
> >   * 法幣互換損失 (Fiat to Fiat Conversion Losses): [美金]
> > 
> > 
> > 4. 其他損益部分:
> > 
> > 
> > * 總其他損益 (Total Other Gains/Losses): [美金]
> > * 細節:
> >   
> >   * 投資損益 (Investment Gains/Losses): [美金]
> >   * 外匯損益 (Forex Gains/Losses): [美金]
> >   * 加密貨幣損益 (Cryptocurrency Gains/Losses): [美金]
> >     
> >     * 加密貨幣損益總額 (Total Cryptocurrency Gains/Losses in USD): [美金]
> >     * 細節:
> >       
> >       * [幣種]:
> >         
> >         * 數量: [數量]
> >         * 成本價值/持有價值: [美金]
> > 
> > 
> > 5. 淨利潤 (Net Profit or Loss): [美金]
> > 
> > 簽署 (Signed): 日期 (Date):
> 
> 這是我前面損益表裡面列出來的收入，還有一個 spreadFee API 裡面有提供但是你的excel 沒有，spreadFee應該要在 excel 補上，otherIncome 可以移除 <img alt="Screenshot 2023-09-06 at 2 04 40 PM" width="914" src="https://user-images.githubusercontent.com/17249354/265908715-f1641248-3ff5-40c8-b133-c60fb58a977e.png">

以下為更改後的對照表，資料沒有缺少，我這邊確認回傳結果ok

![image](https://github.com/CAFECA-IO/BAIFA/assets/20677913/932554ba-743b-4309-8650-0decb4f1e272)

**Comment by TzuHanLiang** [comment]
移除後 otherIncome 後的版本
```json
{
    "success": true,
    "code": "00000000",
    "reason": "ERROR_MESSAGE.SUCCESS",
    "data": {
        "id": "comprehensive_icome-1693872000_1693958399",
        "startDate": "2023-08-05T16:00:00.000Z",
        "endDate": "2023-09-04T16:00:00.000Z",
        "income": {
            "weightedAverageCost": 5170.671840689536,
            "details": {
                "transactionFee": {
                    "totalAmountFairValue": 0,
                    "weightedAverageCost": 0,
                    "breakdown": {
                        "USDT": {
                            "currencyType": "CRYPTOCURRENCY",
                            "name": "USDT",
                            "amount": 0,
                            "weightedAverageCost": 0,
                            "fairValue": 0
                        }
                    }
                },
                "spreadFee": {
                    "totalAmountFairValue": 5084.259880689536,
                    "weightedAverageCost": 5084.259880689536,
                    "breakdown": {
                        "USDT": {
                            "currencyType": "CRYPTOCURRENCY",
                            "name": "USDT",
                            "amount": 5084.259880689536,
                            "weightedAverageCost": 5084.259880689536,
                            "fairValue": 5084.259880689536
                        }
                    }
                },
                "guaranteedStopFee": {
                    "totalAmountFairValue": 86.41196,
                    "weightedAverageCost": 86.41196,
                    "breakdown": {
                        "USDT": {
                            "currencyType": "CRYPTOCURRENCY",
                            "name": "USDT",
                            "amount": 86.41196,
                            "weightedAverageCost": 86.41196,
                            "fairValue": 86.41196
                        }
                    }
                },
                "liquidationFee": {
                    "totalAmountFairValue": 0,
                    "weightedAverageCost": 0,
                    "breakdown": {
                        "USDT": {
                            "currencyType": "CRYPTOCURRENCY",
                            "name": "USDT",
                            "amount": 0,
                            "weightedAverageCost": 0,
                            "fairValue": 0
                        }
                    }
                },
                "withdrawalFee": {
                    "totalAmountFairValue": 0,
                    "weightedAverageCost": 0,
                    "breakdown": {
                        "USDT": {
                            "currencyType": "CRYPTOCURRENCY",
                            "name": "USDT",
                            "amount": 0,
                            "weightedAverageCost": 0,
                            "fairValue": 0
                        }
                    }
                },
                "depositFee": {
                    "totalAmountFairValue": 0,
                    "weightedAverageCost": 0,
                    "breakdown": {
                        "USDT": {
                            "currencyType": "CRYPTOCURRENCY",
                            "name": "USDT",
                            "amount": 0,
                            "weightedAverageCost": 0,
                            "fairValue": 0
                        }
                    }
                }
            }
        },
        "costs": {
            "weightedAverageCost": 0,
            "details": {
                "technicalProviderFee": 0,
                "marketDataProviderFee": 0,
                "newCoinListingCost": 0
            }
        },
        "operatingExpenses": {
            "weightedAverageCost": 0,
            "details": {
                "salaries": 0,
                "rent": 0,
                "marketing": 0,
                "commissionRebates": {
                    "totalAmountFairValue": 0,
                    "weightedAverageCost": 0,
                    "breakdown": {
                        "ETH": {
                            "currencyType": "CRYPTOCURRENCY",
                            "name": "ETH",
                            "amount": 0,
                            "weightedAverageCost": 0,
                            "fairValue": 0
                        },
                        "BTC": {
                            "currencyType": "CRYPTOCURRENCY",
                            "name": "BTC",
                            "amount": 0,
                            "weightedAverageCost": 0,
                            "fairValue": 0
                        },
                        "USDT": {
                            "currencyType": "CRYPTOCURRENCY",
                            "name": "USDT",
                            "amount": 0,
                            "weightedAverageCost": 0,
                            "fairValue": 0
                        }
                    }
                }
            }
        },
        "financialCosts": {
            "weightedAverageCost": 0,
            "details": {
                "interestExpense": 0,
                "cryptocurrencyForexLosses": 0,
                "fiatToCryptocurrencyConversionLosses": 0,
                "cryptocurrencyToFiatConversionLosses": 0,
                "fiatToFiatConversionLosses": 0
            }
        },
        "otherGainsLosses": {
            "weightedAverageCost": 0,
            "details": {
                "investmentGains": 0,
                "forexGains": 0,
                "cryptocurrencyGains": {
                    "totalAmountFairValue": 0,
                    "weightedAverageCost": 0,
                    "breakdown": {
                        "ETH": {
                            "currencyType": "CRYPTOCURRENCY",
                            "name": "ETH",
                            "amount": 0,
                            "weightedAverageCost": 0,
                            "fairValue": 0
                        },
                        "BTC": {
                            "currencyType": "CRYPTOCURRENCY",
                            "name": "BTC",
                            "amount": 0,
                            "weightedAverageCost": 0,
                            "fairValue": 0
                        },
                        "USDT": {
                            "currencyType": "CRYPTOCURRENCY",
                            "name": "USDT",
                            "amount": 0,
                            "weightedAverageCost": 0,
                            "fairValue": 0
                        }
                    }
                }
            }
        },
        "netProfit": 5170.671840689536
    }
}
```
