### ISSUE TITLE
調整 Statements of Cash Flows

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#193]
Ref
- [Excel](https://docs.google.com/spreadsheets/d/1Dm3GMikIMrU9Fv5TeIgjwtN9oIpK43Tw5dzdEZ-C9Ow/edit#gid=54279496)
- [PDF](https://soul-quenching.notion.site/Cash-Flows-Statements-1-00aa081815b84486a8f421d4d096831a#566888da4c0b42079c6ebed5d616c1dc)

**Comment by Julian0701** [comment]
- take 5 hrs

**Comment by arealclimber** [comment]
確認實作與文件相符
