### ISSUE TITLE
調整 Comprehensive Income Statements

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#194]
Ref
- [Excel](https://docs.google.com/spreadsheets/d/1Dm3GMikIMrU9Fv5TeIgjwtN9oIpK43Tw5dzdEZ-C9Ow/edit#gid=614166987)
- [PDF](https://soul-quenching.notion.site/Comprehensive-Income-Statements-1-3722ca5634f04ff0b295ce6fe4984e7f#5344b662e7de4fbf8c522f1d4f9ac74d)

**Comment by Julian0701** [comment]
- take 3 hrs

**Comment by arealclimber** [comment]
檢查過程中發現文件有誤， total amount 無論數字為何都應該是 —，文件已更改，請幫忙調整 

![image](https://github.com/CAFECA-IO/BAIFA/assets/20677913/e3d75738-b33a-4b46-b198-94fb60701e8e)


- [PDF](https://www.notion.so/soul-quenching/Comprehensive-Income-Statements-1-3722ca5634f04ff0b295ce6fe4984e7f)
- [Excel](https://docs.google.com/spreadsheets/d/1Dm3GMikIMrU9Fv5TeIgjwtN9oIpK43Tw5dzdEZ-C9Ow/edit#gid=614166987)

**Comment by arealclimber** [comment]
taking 0.5 hrs
與文件相符
