### ISSUE TITLE
綜合損益表內容補充

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#323]
ref: 

- #266 
- [Notion](https://www.notion.so/soul-quenching/Comprehensive-Income-Statements-3-5e406e0534ad4421bf244e565cd47a42?pvs=4)
- [excel](https://docs.google.com/spreadsheets/d/1zdzNVgPzwQFr6FxfKMOa_AF0pt7WKjUvSbFaZ19u85A/edit#gid=614166987)
- 反白是筆記用途，報表上不用跟著調整

**Comment by Julian0701** [comment]
- take 1 hr

**Comment by arealclimber** [comment]
- 發現有些錯誤是來自文件格式參差不齊，包括大寫跟複數 s 不全部一致的地方，現在綜合損益表跟現金流量表文件已更正完畢

# Comprehensive income

1. 麻煩幫我把圈起來的部分，改成只有第一個字大寫，除了截圖之外的其餘細項也麻煩跟著調整，請參考修正後的 [excel](https://docs.google.com/spreadsheets/d/1zdzNVgPzwQFr6FxfKMOa_AF0pt7WKjUvSbFaZ19u85A/edit#gid=614166987)
![image](https://github.com/CAFECA-IO/BAIFA/assets/20677913/9e111fd4-76d4-4967-b9c9-ac9c0322e7b1)
![image](https://github.com/CAFECA-IO/BAIFA/assets/20677913/f876122d-0b0e-4614-826e-8d0f7095e11d)

**Comment by Julian0701** [comment]
- take 0.5 hr
