### ISSUE TITLE
現金流量表內容補充

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#328]
ref:

- #269 
- [Notion](https://soul-quenching.notion.site/Cash-Flows-Statements-3-f8d3200eaf3348e396c69ea398f80a33?pvs=4)
- [excel](https://docs.google.com/spreadsheets/d/1zdzNVgPzwQFr6FxfKMOa_AF0pt7WKjUvSbFaZ19u85A/edit#gid=54279496)
- [備註](https://docs.google.com/spreadsheets/d/1B6ZzcpxLq6oBhU9ClTsWJ1tbmfntnxCXHwqgNlKlKMs/edit#gid=717396730)

**Comment by Julian0701** [comment]
- take 5 hrs

**Comment by arealclimber** [comment]
- 發現有些錯誤是來自文件格式參差不齊，包括大寫跟複數 s 不全部一致的地方，現在綜合損益表跟現金流量表文件已更正完畢

1. 麻煩幫我把 Statements of Cash Flow 改成 **Statements of Cash Flows**
(現金流量表有兩種表達方式，一個是 Cash flow statement，另一個是 Statements of Cash Flows)
![image](https://github.com/CAFECA-IO/BAIFA/assets/20677913/b122b282-2fbe-4c32-bedb-a04a6fb9d9dc)
![image](https://github.com/CAFECA-IO/BAIFA/assets/20677913/8d465d86-747f-4fd9-b331-c66b68a033da)


1. 麻煩幫我把圈起來的部分，改成只有第一個字大寫，除了截圖之外的其餘細項也麻煩跟著調整，請參考修正後的 [excel](https://docs.google.com/spreadsheets/d/1zdzNVgPzwQFr6FxfKMOa_AF0pt7WKjUvSbFaZ19u85A/edit#gid=54279496)
![image](https://github.com/CAFECA-IO/BAIFA/assets/20677913/b3a77e00-71d2-4b47-b29f-b0742924a83c)

2. 需要修正成 `Cash received from customers as transaction fees`


![image](https://github.com/CAFECA-IO/BAIFA/assets/20677913/0af0ed58-a7ff-4dba-aff4-81b6a8c3fb42)

**Comment by Julian0701** [comment]
- take 0.5 hr
