### ISSUE TITLE
報表內容調整

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#343]
- [x]  #342

**Comment by Julian0701** [comment]
- take 1 hr

**Comment by arealclimber** [comment]
## balance sheet

- 總表需要加上 Other capital reserve 欄位
- 總表的 A020 Account receivable 請修正成 A020 Accounts receivable，文件有誤已更改
- 細項的第一個欄位跟加總欄位需要加上 `$` ，除了 Other capital reserve 以外，還有 User deposits, Account receivable, accounts receivable, accounts payable, retained earnings 沒有加到

![Screenshot 2023-11-30 at 09 24 42](https://github.com/CAFECA-IO/BAIFA/assets/20677913/060b4966-c93c-4c42-b0e5-389407c320ea)
![Screenshot 2023-11-30 at 09 33 42](https://github.com/CAFECA-IO/BAIFA/assets/20677913/2b61885e-a7c8-4d58-90ad-b1aa36035051)

## cash flow statement

- 細項的第一個欄位跟加總欄位需要加上 $ ，有一些第一個欄位貨加總欄位沒加上，請幫忙補上

![Screenshot 2023-11-30 at 09 36 13](https://github.com/CAFECA-IO/BAIFA/assets/20677913/59305726-5b62-4712-a0b2-bff14ba4c847)

**Comment by Julian0701** [comment]
已修改完成
- take 1  hr

**Comment by arealclimber** [comment]
需要修改的地方如以下圖示，其中 comprehensive income statement 文件有誤已補上
# balance sheet
![image](https://github.com/CAFECA-IO/BAIFA/assets/20677913/fb785f0c-af82-43fb-9f42-bae3d10f4d1d)


# comprehensive income statement
![image](https://github.com/CAFECA-IO/BAIFA/assets/20677913/69338755-0e73-47ae-bdc8-193c03e16cef)

**Comment by Julian0701** [comment]
已補上 $ 
- take 0.5 hr
