### ISSUE TITLE
初步驗證 API / Mock API / Postman 可否使用

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/BAIFA#355]
初步驗證 API / Mock API / Postman 可否使用

參照：
- API 規格文件位置 : [API v1.1.0](https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0)
- 參考 issues : 
#351 
#352 
#359 

步驟：
- [x] 確認 Mock API Codes 與 API Documentation 是否一致
- [x] 確認 Postman Request URL, Response content 與 API Documentation 是否一致
- [x] Mock API PR

**Comment by godmmt** [comment]
took 1 pt
remain 1 pt

- [ ] 等 #359 完成後再做一次驗證

**Comment by godmmt** [comment]
TODO :
- [ ] 等 #359 完成後再做一次驗證

**Comment by godmmt** [comment]
確認 Mock API Codes 與 API Documentation 是否一致
---
- [ ] 001 - GET /app
- [ ] 002 - GET /app/suggestions?search_input=${searchInput}
- [ ] 003 - GET /app/search?search_input=${searchInput}
---
- [ ] 004 - GET /app/chains
- [ ] 005 - GET /app/chains/:chainId
- [ ] 006 - GET /app/chains/:chainId/blocks?start_date=${startTimestamp}&end_date=${endTimestamp}
- [ ] 007 - GET /app/chains/:chainId/blocks/:blockId
- [ ] 008 - GET /app/chains/:chainId/blocks/:blockId/transactions
---
- [ ] 009 - GET /app/chains/:chainId/transactions
- [ ] 010 - GET /app/chains/:chainId/transactions/:transactionId
---
- [ ] 011 - GET /app/chains/:chainId/addresses/:addressId
- [ ] 012 - GET /app/chains/:chainId/addresses/:addressId/reviews
- [ ] 013 - GET /app/chains/:chainId/addresses/:addressId/red-flags
- [ ] 014 - GET /app/chains/:chainId/addresses/:addressId/interactions?type=address
---
- [ ] 015 - GET /app/chains/:chainId/contracts/:contractId
- [ ] 016 - GET /app/chains/:chainId/evidence/:evidenceId
---
- [ ] 017 - GET /app/currencies
- [ ] 018 - GET /app/currencies/:currencyId
- [ ] 019 - GET /app/currencies/:currencyId/red-flags
---
- [ ] 020 - GET /app/blacklist
- [ ] 021 - GET /app/red-flags
- [ ] 022 - GET /app/red-flags/:redFlagId

**Comment by godmmt** [comment]
- [ ] 確認 Postman Request URL, Response content 與 API Documentation 是否一致

- [ ] 001-010
- [ ] 011-022

**Comment by godmmt** [comment]
## Mock API PR

### PR Rule:
https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/code-review.md

### PR Example:
https://github.com/CAFECA-IO/TideBit-DeFi/pull/156

- [ ] DONE

**Comment by godmmt** [comment]
疑問
---
PR CHECK LIST:
[Naming convention](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md) verification

api/v1/app/red-flags 的 red-flags 
需要依照 Naming convention 文件中的 File and Folder 規定使用 snake_case 嗎？
意思就是：要改成 api/v1/app/red_flags 嗎？

目前我的 api 目錄底下的目錄和檔案
命名方式是依照 API URL格式：
- Folder : 烤肉串 red-flags
- File : 
  - 動態參數 API 文件：小駝峰 [redFlagsId].ts
  - API 文件：烤肉串 red-flags.ts

**Comment by Luphia** [comment]
需要，檔名應遵守[Naming convention](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md)，故調整為 api/v1/app/red_flags

**Comment by godmmt** [comment]
# 修改檔名

需變更的內容：

- [ ] API Document : [API v1.1.0](https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0)
- [ ] Mock API codes
- [ ] Postman

**Comment by godmmt** [comment]
- PR : https://github.com/CAFECA-IO/BAIFA/pull/366
