### ISSUE TITLE
串接 Mock API (1/2)

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#369]
[API v1.1.0](https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0)
- [x] 001 - Homepage Data
- [x] 002 - Search suggestions (關鍵字提示)
- [x] 003 - Search Result
- [x] 004 - Get data from chains
- [x] 005 - Get all data from a chain
- [x] 006 - Select period for blocks
- [x] 007 - Get a block data from a chain
- [x] 008 - Transaction List from a block
- [x] 009 - Select period for transactions / Transaction History from Addresses
- [x] 010 - Get a transaction data from a chain
- [x] 011 - Get an address data from a chain
- [x] 012 - Reviews of an address

**Comment by Julian0701** [comment]
- 排版 & 整理 context 導致花費比預估更多的時間
- take 8 hrs, remain 8 hrs
- [ ] [cross-origin header](https://blog.logrocket.com/using-cors-next-js-handle-cross-origin-requests/)

**Comment by Julian0701** [comment]
- take 8 hrs, remain 5 hrs
- 加上 cross-origin header, 等 merge 後驗證
- 剩下 009, 011, 012 ，需要確認 006 的範圍

**Comment by Julian0701** [comment]
- take 2.5 hrs
- 需要調整的部分： #383 , #384 , #387

**Comment by godmmt** [comment]
- 關於 toAddressId 要修改為 from / to 的部分，我找到還有 010 這支，我有開單給我自己囉 #391
