### ISSUE TITLE
API 調整：006 Select period for blocks

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#383]
[API v1.1.0](https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0)
006 的回傳內容應該如下：
```json
[
   {
      "id": "230020",
      "chainId": "isun",
      "createdTimestamp": 1673940795,
      "stability": "MEDIUM"
    },
    {
      "id": "230021",
      "chainId": "isun",
      "createdTimestamp": 1679978900,
      "stability": "HIGH"
    },
    {
      "id": "230022",
      "chainId": "isun",
      "createdTimestamp": 1680176231,
      "stability": "LOW"
    }
]
```

- [x] Done

**Comment by godmmt** [comment]
Update steps:

- [ ] API Document - [API v1.1.0](https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0)
- [ ] Mock API codes
- [ ] Postman config

**Comment by godmmt** [comment]
Another update:

- [ ] API - 011 add Review Score
- [ ] API icon image path 
![image](https://github.com/CAFECA-IO/BAIFA/assets/105651918/4ad038fd-a5d2-4496-9e4e-475c8d6316d9)

**Comment by godmmt** [comment]
Update steps:

- [ ] API Document - [API v1.1.0](https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0)
- [ ] Mock API codes
- [ ] Postman config

**Comment by godmmt** [comment]
- PR : #386

**Comment by godmmt** [comment]
done.

took 2 hours
