### ISSUE TITLE
[VERIFY] 驗算頁面開發規劃的點數

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/BAIFA#4]
# ref:
- [設計稿](https://www.figma.com/file/gC4On1ULcel7UzXMwdS9cY/BOLT-explorer?type=design&node-id=469-58157)
- [Jodie 的螢幕錄影](https://github.com/CAFECA-IO/boltchain.io/issues/177)
- [Julian 的點數評估](https://github.com/CAFECA-IO/boltchain.io/issues/178)

**Comment by Luphia** [comment]
- deprecated mission
