### ISSUE TITLE
設定 PreCommit 機制 Error

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/BAIFA#417]
此為 https://github.com/CAFECA-IO/BAIFA/issues/411 的延伸問題

# [ 問題 ]‼️
[設定 PreCommit 機制](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/newbie/development-environment.md#22-%E8%A8%AD%E5%AE%9A-precommit-%E6%A9%9F%E5%88%B6)

建立 PreCommit 後，我會在最後一個 hook 失敗（`- id: pretty-format-json //檢查 json 格式是否整齊`）
可能是因為我 commit 內容包含 package.json
此問題目前尚未解決

# 重現 PreCommit 機制 Error

1. 打開最後一條 hook ( `- id: pretty-format-json //檢查 json 格式是否整齊`) : 
![截圖 2023-12-28 下午5 44 43](https://github.com/CAFECA-IO/BAIFA/assets/105651918/7d59413f-6a01-4745-83e3-3c349e41621b)

2. 編輯 package.json (增加版號) :
![截圖 2023-12-28 下午5 45 24](https://github.com/CAFECA-IO/BAIFA/assets/105651918/907a94f1-dd35-402f-9992-abfeb0b12ddb)

3. commit Failed!
![截圖 2023-12-28 下午5 43 02](https://github.com/CAFECA-IO/BAIFA/assets/105651918/bd8e9de0-d14d-492d-8794-11cb3a885225)

4. Git Error : 
```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
check yaml...............................................................Passed
check json...............................................................Passed
check xml............................................(no files to check)Skipped
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
pretty format json.......................................................Failed
- hook id: pretty-format-json
- exit code: 1

--- package.json
+++ package.json
@@ -1,17 +1,4 @@
 {
-  "name": "chat-bot-lizzz",
-  "version": "0.1.2",
-  "private": true,
-  "scripts": {
-    "dev": "next dev",
-    "build": "next build",
-    "start": "next start",
-    "test": "jest --coverage",
-    "lint": "eslint --ignore-path .gitignore .",
-    "check-format": "prettier --ignore-path .gitignore --list-different \"**/*.+(js|ts|json)\"",
-    "format": "prettier --ignore-path .gitignore --write \"**/*.+(js|ts|json)\"",
-    "validate": "npm run test && npm run check-format && npm run lint"
-  },
   "dependencies": {
     "next": "14.0.4",
     "react": "^18",
@@ -45,5 +32,18 @@
     "hooks": {
       "pre-commit": "npm run test && lint-staged"
     }
-  }
+  },
+  "name": "chat-bot-lizzz",
+  "private": true,
+  "scripts": {
+    "build": "next build",
+    "check-format": "prettier --ignore-path .gitignore --list-different \"**/*.+(js|ts|json)\"",
+    "dev": "next dev",
+    "format": "prettier --ignore-path .gitignore --write \"**/*.+(js|ts|json)\"",
+    "lint": "eslint --ignore-path .gitignore .",
+    "start": "next start",
+    "test": "jest --coverage",
+    "validate": "npm run test && npm run check-format && npm run lint"
+  },
+  "version": "0.1.2"
 }
```

**Comment by arealclimber** [comment]
# 錯誤原因
- 設定了兩種 pre-commit ，這兩種 pre-commit 都有 json 檔案設定，所以彼此起衝突， 用 yaml 執行的 pre-commit 無法矯正排版，所以才有錯誤訊息
```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
check yaml...............................................................Passed
check json...............................................................Passed
check xml............................................(no files to check)Skipped
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
pretty format json.......................................................Failed
- hook id: pretty-format-json
- exit code: 1

--- package.json
+++ package.json
@@ -1,17 +1,4 @@
...
```

# 解決方法
- 把 `.prettierrc` 改成 `.prettierrc.yaml`
- 更改 `.pre-commit-config.yaml` ，讓我們自己的排版規則取代 `pretty-format-json`
- 之後每次開發，在更改檔案之後，執行指令 `pre-commit run --all-files` ，如果排版不符合規定，會先出現提示訊息代表 pre-commit 透過 yaml 幫忙排版，之後再執行一次 `pre-commit run --all-files` 確保所有步驟都成功，就能 commit 
![image](https://github.com/CAFECA-IO/BAIFA/assets/20677913/92b8f430-6e71-4cc0-ad31-ffecbde582d2)



taking 1.5 hrs

**Comment by arealclimber** [comment]
- 修改完之後，可以看到被排版的檔案
    - [PR commit (app.tsx & index.tsx)](https://github.com/CAFECA-IO/chat-bot-lizzz/pull/1/commits/b82eda2d2ab78a1f5ba058d6f9c4f2de8472af09#diff-18e0d4553c97cfc420e938ccafb4e3a688e782fa4512ba4ceae3e2a6f24c1987)

**Comment by godmmt** [comment]
@arealclimber 
我看到妳[這裡](https://github.com/CAFECA-IO/BAIFA/issues/417#issuecomment-1871710391)`.prettierrc.yaml`：
```yaml
$schema: http://json.schemastore.org/prettierrc
arrowParens: avoid
bracketSpacing: true
jsxSingleQuote: false
printWidth: 100
proseWrap: always
quoteProps: as-needed
semi: true
singleQuote: true
tabWidth: 2
trailingComma: es5
useTabs: false
plugins:
  - prettier-plugin-tailwindcss
```

其中 `bracketSpacing: true`

但妳發的 PR 是設定為 `bracketSpacing: false`
![截圖 2023-12-29 下午3 38 32](https://github.com/CAFECA-IO/BAIFA/assets/105651918/43adad64-c745-4bcf-bcb5-ae5813e6d6db)


請問是依哪個為主？🤔

**Comment by arealclimber** [comment]
@godmmt 

根據之前因應 Airbnb ESLint rules 修改的 .prettierrc， `bracketSpacing: true` 才是正確的，參考 https://github.com/CAFECA-IO/KnowledgeManagement/issues/49#issuecomment-1869953548

但 [PR](https://github.com/CAFECA-IO/chat-bot-lizzz/pull/1) 只是為了修改 pre-commit 錯誤，我只有把你原本的 prettier 轉檔 ，保留你原本的設定

**Comment by arealclimber** [comment]
[更新 KM](https://github.com/CAFECA-IO/KnowledgeManagement/blob/master/survey/PreCommit.md#%E6%90%AD%E9%85%8D-work-guidelines-%E7%9A%84-pre-commit)

**Comment by godmmt** [comment]
took 3 hours

done.

**Comment by godmmt** [comment]
已修復 Error，謝謝。

took 2 hours

done.
