### ISSUE TITLE
Blockchain Explorer - 001 - Homepage Data

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA#428]
API v1.1.0
https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0

001 - Homepage Data
HTTP Request: GET /app

Parameters: none

Request Example: GET /app

Response Example:

{
  "chains": 5,
  "cryptoCurrencies": 5,
  "blackList": 7
}

**Comment by Julian0701** [comment]
- take 6 hrs, remain 3 hrs

- 連接上 BAIFA DB 了，但資料庫裡還沒有相關的資料，不確定下一步該怎麼做

![image](https://github.com/CAFECA-IO/BAIFA/assets/114177573/8b1ef7c1-dd0a-4018-aec4-accee835cce1)

<img width="679" alt="image" src="https://github.com/CAFECA-IO/BAIFA/assets/114177573/620552c6-4830-4d35-916d-d835493a261c">

**Comment by Julian0701** [comment]
- take 0.5 hrs
