### ISSUE TITLE
Blockchain Explorer - 002 - Search suggestions (關鍵字提示)

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA#429]
API v1.1.0
https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0

002 - Search suggestions (關鍵字提示)
HTTP Request: GET /app/suggestions?search_input=${searchInput}

Parameters: search_input - required*

Request Example: GET /app/suggestions?search_input=11

Response Example:

{
  "suggestions": ["110029", "113248", "114007", "115588"]
}

**Comment by arealclimber** [comment]
taking 5 hrs
- [x]  transaction_receipt_raw
    - [x]  contract_address
- [x]  contracts
    - [x]  contract_address
    - [x]  creator_address

remaining 2 hrs
- 還缺少 block, evidence, transaction, red flag of address

**Comment by arealclimber** [comment]
taking 1 hr

**Comment by arealclimber** [comment]
- contracts
    - [x]  contract_address
    - [x]  creator_address
- evidences
    - [x]  evidence_id
- transactions
    - [x]  from_address
    - [x]  to_address
    - [x]  hash
- ~red_flags~
    - [x]  related_addresses
- blocks
    - [x]  hash
