### ISSUE TITLE
AllChainPageBody

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#43]
[Mockup](https://www.figma.com/proto/gC4On1ULcel7UzXMwdS9cY/BAIFAAA?type=design&node-id=307-27480&scaling=scale-down&page-id=46%3A771&starting-point-node-id=46%3A772)

包含標題(Chain name)、ChainSelectorBox、Breadcrumb

**Comment by Luphia** [comment]
- deprecated mission
