### ISSUE TITLE
Blockchain Explorer - 003 - Search Result

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA#430]
API v1.1.0
https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0

003 - Search Result
HTTP Request: GET /app/search?search_input=${searchInput}

Parameters: search_input - required*

Request Example: GET /app/search?search_input=10

Response Example:

[
  {
    "type": "BLOCK",
    "data": {
      "id": "210018",
      "chainId": "btc",
      "createdTimestamp": 1665798400,
      "stability": "MEDIUM"
    }
  },
  {
    "type": "ADDRESS",
    "data": {
      "id": "148208",
      "chainId": "usdt",
      "createdTimestamp": 1682940241,
      "address": "0x278432201",
      "flaggingCount": 10,
      "riskLevel": "MEDIUM_RISK"
    }
  },
  {
    "type": "CONTRACT",
    "data": {
      "id": "314839",
      "chainId": "btc",
      "createdTimestamp": 1681918401,
      "contractAddress": "0x444357813"
    }
  },
  {
    "type": "EVIDENCE",
    "data": {
      "id": "528401",
      "chainId": "eth",
      "createdTimestamp": 1680421348,
      "evidenceAddress": "0x898765432"
    }
  },
  {
    "type": "TRANSACTION",
    "data": {
      "id": "924044",
      "chainId": "eth",
      "createdTimestamp": 1684482143,
      "hash": "0x213456789"
    }
  },
  {
    "type": "BLACKLIST",
    "data": {
      "id": "142523",
      "chainId": "usdt",
      "createdTimestamp": 1684801889,
      "address": "0x270183713",
      "publicTag": ["PUBLIC_TAG.HACKER"]
    }
  },
  {
    "type": "RED_FLAG",
    "data": {
      "id": "1138290086",
      "chainId": "btc",
      "createdTimestamp": 1689244021,
      "interactedAddresses": [
        {
          "id": "122134",
          "chainId": "eth"
        },
        {
          "id": "134325",
          "chainId": "usdt"
        }
      ],
      "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_RECEIVES"
    }
  }
  // ... other result
]

**Comment by arealclimber** [comment]
- [ ] 將 search result 的資料格式調整成好懂易維護的格式
- [ ]

**Comment by arealclimber** [comment]
### search

- block
    - [x]  table: blocks
        - [x]  search: hash
        - [x]  search: id
- address
    - [x]  table: addresses
        - [x]  search: address
        - [x]  search: id
    - [x]  table: red_flags
        - [x]  search: related_addresses
- contract
    - [x]  table: contracts
        - [x]  search: contract_address
- evidence
    - [x]  table: evidences
        - [x]  search: contract_address
- transaction
    - [x]  table: transactions
        - [x]  search: hash
- red flag
    - [x]  table: red_flags
        - [x]  search: related_addresses
- blacklist
    - [x]  table: black_lists
        - [x]  search: address_id when we have addresses as search result from input (address string)
        - [x]  search: address_id when users don’t type string address and type addressId instead (number)
