### ISSUE TITLE
Blockchain Explorer - 004 - Get data from chains

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA#431]
API v1.1.0
https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0

004 - Get data from chains
HTTP Request: GET /app/chains

Parameters: none

Request Example: GET /app/chains

Response Example:

[
  {
    "chainId": "eth",
    "chainName": "Ethereum",
    "chainIcon": "/currencies/eth.svg",
    "blocks": 56789,
    "transactions": 123456
  },
  {
    "chainId": "bit",
    "chainName": "Bitcoin",
    "chainIcon": "/currencies/btc.svg",
    "blocks": 67890,
    "transactions": 987654
  },
  {
    "chainId": "isun",
    "chainName": "iSunCloud",
    "chainIcon": "/currencies/isun.svg",
    "blocks": 17313,
    "transactions": 917361
  },
  {
    "chainId": "usdt",
    "chainName": "Tether",
    "chainIcon": "/currencies/usdt.svg",
    "blocks": 34567,
    "transactions": 567890
  },
  {
    "chainId": "bnb",
    "chainName": "Binance",
    "chainIcon": "/currencies/bnb.svg",
    "blocks": 45678,
    "transactions": 789012
  }
  // ... other chains
]

**Comment by Julian0701** [comment]
- take 5 hrs
![image](https://github.com/CAFECA-IO/BAIFA/assets/114177573/136d8a1f-ecaa-4f4c-bce5-0da1aba8a57b)

DB 須補上 blocks 和 transactions 欄位
