### ISSUE TITLE
Blockchain Explorer - 005 - Get all data from a chain

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA#432]
API v1.1.0
https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0

005 - Get all data from a chain
HTTP Request: GET /app/chains/:chain_id

Parameters: none

Request Example: GET /app/chains/isun

Response Example:

{
  "chainId": "isun",
  "chainName": "iSunCloud",
  "chainIcon": "/currencies/isun.svg",
  "blockData": [
    {
      "id": "230020",
      "chainId": "isun",
      "createdTimestamp": 1673940795,
      "stability": "MEDIUM"
    },
    {
      "id": "230021",
      "chainId": "isun",
      "createdTimestamp": 1679978900,
      "stability": "HIGH"
    },
    {
      "id": "230022",
      "chainId": "isun",
      "createdTimestamp": 1680176231,
      "stability": "LOW"
    }
    //...
  ],
  "transactionData": [
    {
      "id": "930071",
      "chainId": "isun",
      "createdTimestamp": 1607957394,
      "from": [
        { "type": "address", "address": "130294" }
        // FIXME:address like 0x356f9537631A773Ab9069fEc25f74Cd884132776
      ],
      "to": [
        { "type": "contract", "address": "310071" }
        // FIXME:address like 0x356f9537631A773Ab9069fEc25f74Cd884132776
      ],
      "type": "Crypto Currency",
      "status": "SUCCESS"
    },
    {
      "id": "930291",
      "chainId": "isun",
      "createdTimestamp": 1679978900,
      "from": [
        { "type": "address", "address": "130682" }
        // ...
        // FIXME:address like 0x356f9537631A773Ab9069fEc25f74Cd884132776
      ],
      "to": [
        { "type": "contract", "address": "310071" }
        // FIXME:address like 0x356f9537631A773Ab9069fEc25f74Cd884132776
      ],
      "type": "Evidence",
      "status": "FAILED"
    },
    {
      "id": "930032",
      "chainId": "isun",
      "createdTimestamp": 1680176231,
      "from": [
        { "type": "address", "address": "130008" }
        // FIXME:address like 0x356f9537631A773Ab9069fEc25f74Cd884132776
      ],
      "to": [
        { "type": "contract", "address": "310029" }
        // FIXME:address like 0x356f9537631A773Ab9069fEc25f74Cd884132776
      ],
      "type": "NFT",
      "status": "PENDING"
    }
    //...
  ]
}

**Comment by Julian0701** [comment]
- take 5 hrs
