### ISSUE TITLE
Blockchain Explorer - 006 - Select period for blocks

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA#433]
API v1.1.0
https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0

006 - Select period for blocks
HTTP Request: GET /app/chains/:chain_id/blocks?start_date=${startTimestamp}&end_date=${endTimestamp}

Parameters: start_date and end_date - required* (根據時間區段回傳資料)

Request Example: GET /app/chains/isun/blocks?start_date=1680176231&end_date=1679978900

Response Example:

[
  {
    "id": "230020",
    "chainId": "isun",
    "createdTimestamp": 1673940795,
    "stability": "MEDIUM"
  },
  {
    "id": "230021",
    "chainId": "isun",
    "createdTimestamp": 1679978900,
    "stability": "HIGH"
  },
  {
    "id": "230022",
    "chainId": "isun",
    "createdTimestamp": 1680176231,
    "stability": "LOW"
  }
]

**Comment by Julian0701** [comment]
- take 3 hrs, remain 2 hrs
- 缺 stability(穩定性) 欄位
- DB 的 chain_id、start_date、end_date 的 type 和前端不符，須討論接下來的做法

**Comment by Julian0701** [comment]
- take 2 hrs
