### ISSUE TITLE
Blockchain Explorer - 007 - Get a block data from a chain

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA#434]
API v1.1.0
https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0

007 - Get a block data from a chain
HTTP Request: GET /app/chains/:chain_id/blocks/:block_id

Parameters: none

Request Example: GET /app/chains/isun/blocks/230021

Response Example:

{
  "id": "230021",
  "chainId": "isun",
  "chainIcon": "/currencies/isun.svg",
  "stability": "HIGH", //"MEDIUM" | "HIGH" | "LOW"
  "createdTimestamp": 1679978900,
  "managementTeam": ["Alice", "Bob", "Charlie"],
  "transactionCount": 25,
  "miner": "0x1234567890",
  "reward": 2.5,
  "uint": "isun",
  "size": 3523, //bytes
  "previousBlockId": "230020",
  "nextBlockId": "230022"
}

**Comment by Julian0701** [comment]
- take 3 hrs
