### ISSUE TITLE
Blockchain Explorer - 010 - Get a transaction data from a chain

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA#437]
API v1.1.0
https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0

010 - Get a transaction data from a chain
HTTP Request: GET /app/chains/:chain_id/transactions/:transaction_id

Parameters: none

Request Example: GET /app/chains/isun/transactions/930071

Response Example:

{
  "id": "930071",
  "hash": "0xE47Dcf8aF9829AD3c4E31409eB6ECfecd046d1BD",
  "type": "NFT",
  "status": "PROCESSING",
  "chainId": "isun",
  "chainIcon": "/currencies/isun.svg",
  "blockId": "230021",
  "createdTimestamp": 1688342795,
  "from": [{ "type": "address", "address": "130294" }],
  "to": [{ "type": "contract", "address": "310071" }],
  "evidenceId": "530029",
  "value": 0.01,
  "fee": 0.01,
  "flaggingType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_RECEIVES"
}

**Comment by Julian0701** [comment]
- take 3 hrs
