### ISSUE TITLE
Blockchain Explorer - 011 - Get an address data from a chain

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA#438]
API v1.1.0
https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0

011 - Get an address data from a chain
HTTP Request: GET /app/chains/:chain_id/addresses/:address_id

Parameters: none

Request Example: GET /app/chains/btc/addresses/110132

Response Example:

{
  "id": "110132",
  "type": "address",
  "address": "0x2775D3190693fEc256d156f9f74Cd8843A79",
  "chainId": "btc",
  "chainIcon": "/currencies/isun.svg",
  "createdTimestamp": 1680827461,
  "latestActiveTime": 1682935384,
  "relatedAddresses": [
    {
      "id": "214134",
      "chainId": "btc"
    },
    {
      "id": "234143",
      "chainId": "eth"
    }
    // ...
  ],
  "interactedAddressCount": 3,
  "interactedContactCount": 2,
  "score": 2.8,
  "reviewData": [
    {
      "id": "T93015400001",
      "transactionId": "930154",
      "chainId": "btc",
      "createdTimestamp": 1689352795,
      "authorAddressId": "324801",
      "content": "This is a review",
      "stars": 3
    },
    {
      "id": "T93015400002",
      "transactionId": "930154",
      "chainId": "btc",
      "createdTimestamp": 1689752690,
      "authorAddressId": "327923",
      "content": "This is a review",
      "stars": 3
    }
    //...
  ],
  "transactionHistoryData": [
    {
      "id": "918402",
      "chainId": "btc",
      "createdTimestamp": 1679978987,
      "from": [{ "type": "address", "address": "114007" }], // FIXME:address like 0x356f9537631A773Ab9069fEc25f74Cd884132776
      "to": [{ "type": "contract", "address": "110132" }],
      "type": "Evidence",
      "status": "SUCCESS"
    },
    {
      "id": "912299",
      "chainId": "btc",
      "createdTimestamp": 1687909392,
      "from": [{ "type": "address", "address": "110132" }], // FIXME:address like 0x356f9537631A773Ab9069fEc25f74Cd884132776
      "to": [{ "type": "contract", "address": "310683" }],
      "type": "Evidence",
      "status": "FAILED"
    }
    //...
  ],
  "blockProducedData": [
    {
      "id": "217328",
      "createdTimestamp": 1678940724,
      "stability": "MEDIUM",
      "reward": 2.4,
      "uint": "btc",
      "chainIcon": "/currencies/btc.svg"
    },
    {
      "id": "217329",
      "createdTimestamp": 1684176283,
      "stability": "LOW",
      "reward": 2.4,
      "uint": "btc",
      "chainIcon": "/currencies/btc.svg"
    }
    //...
  ],
  "flaggingCount": 23,
  "riskLevel": "MEDIUM_RISK",
  "publicTag": ["PUBLIC_TAG.UNKNOWN_USER"]
}

**Comment by Julian0701** [comment]
- take 3 hrs, remain 2 hrs
- 整理 transactionHistoryData 和 blockProducedData

**Comment by Julian0701** [comment]
- take 2 hrs
