### ISSUE TITLE
ChainSelectorBox

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#44]
[Mockup](https://www.figma.com/proto/gC4On1ULcel7UzXMwdS9cY/BAIFAAA?type=design&node-id=307-27480&scaling=scale-down&page-id=46%3A771&starting-point-node-id=46%3A772)

![截圖 2023-06-19 上午11 51 26](https://github.com/CAFECA-IO/boltchain.io/assets/114177573/ba07b055-ae24-45c3-9d6d-c71e8c1f4ecb)

- 所有區塊鏈的清單
- 用 grid 排版

**Comment by Julian0701** [comment]
- 這部分不細分成個別 component ，放在 AllChainPageBody 裡就可以

**Comment by Luphia** [comment]
- deprecated mission
