### ISSUE TITLE
Blockchain Explorer - 013 - Get red flags data from an Address

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA#440]
Check : 

- [x] [API v1.1.0](https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0) 最新內容更新到此單子敘述
- [ ] done / commit / PR
- [ ] 013 - Get red flags data from an Address

---

## 013 - Get red flags data from an Address

HTTP Request: `GET /app/chains/:chain_id/addresses/:address_id/red_flags`

Parameters: none

Request Example: `GET /app/chains/btc/addresses/115588/red_flags`

Response Example:

```json
[
  {
    "id": "1300200001",
    "chainId": "isun",
    "chainName": "iSunCloud",
    "chainIcon": "/currencies/isun.svg",
    "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_WITHDRAW",
    "createdTimestamp": 1679978900
  },
  {
    "id": "1300200002",
    "chainId": "isun",
    "chainName": "iSunCloud",
    "chainIcon": "/currencies/isun.svg",
    "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_RECEIVES",
    "createdTimestamp": 1680183194
  },
  {
    "id": "1300200003",
    "chainId": "isun",
    "chainName": "iSunCloud",
    "chainIcon": "/currencies/isun.svg",
    "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_LARGE_WITHDRAW",
    "createdTimestamp": 1682194724
  },
  {
    "id": "1300200004",
    "chainId": "isun",
    "chainName": "iSunCloud",
    "chainIcon": "/currencies/isun.svg",
    "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_LARGE_WITHDRAW",
    "createdTimestamp": 1682729103
  }
  // ... other red flags
]
```

**Comment by godmmt** [comment]
# 連線 TablePlus

Download: 使用企業付費版本，從 Setapp 內下載。
Settings:
<img width="500" alt="截圖 2024-01-17 上午11 00 26" src="https://github.com/CAFECA-IO/BAIFA/assets/105651918/5c33a152-c5f2-447b-afdc-f9b28e2af7a5">

**Comment by godmmt** [comment]
latest API doc:


## 013 - Get red flags data from an Address

HTTP Request: `GET /app/chains/:chain_id/addresses/:address_id/red_flags`

Parameters: none

Request Example: `GET /app/chains/btc/addresses/115588/red_flags`

Response Example:

```json
[
  {
    "id": "1300200001",
    "chainId": "isun",
    "chainName": "iSunCloud",
    "chainIcon": "/currencies/isun.svg",
    "addressId": "130020",
    "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_WITHDRAW",
    "createdTimestamp": 1679978900
  },
  {
    "id": "1300200002",
    "chainId": "isun",
    "chainName": "iSunCloud",
    "chainIcon": "/currencies/isun.svg",
    "addressId": "130020",
    "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_RECEIVES",
    "createdTimestamp": 1680183194
  },
  {
    "id": "1300200003",
    "chainId": "isun",
    "chainName": "iSunCloud",
    "chainIcon": "/currencies/isun.svg",
    "addressId": "130020",
    "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_LARGE_WITHDRAW",
    "createdTimestamp": 1682194724
  },
  {
    "id": "1300200004",
    "chainId": "isun",
    "chainName": "iSunCloud",
    "chainIcon": "/currencies/isun.svg",
    "addressId": "130020",
    "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_LARGE_WITHDRAW",
    "createdTimestamp": 1682729103
  }
  // ... other red flags
]
```

**Comment by godmmt** [comment]
# What I Did Today

- 安裝 TablePlus
- 成功連上 DB
- 研究一下 TablePlus 介面

- `red_flags` table 好像只有欄位，沒有資料。
  欄位也少了一些，似乎與 API 規格不一致？🤔😵（不確定）
  <img width="1440" alt="截圖 2024-01-17 下午5 42 15" src="https://github.com/CAFECA-IO/BAIFA/assets/105651918/ef8a2f9a-0ef1-4752-a048-14e9fb5e88c4">

> [!NOTE]
> _想知道要在畫面上，要怎麼測試是否成功將 API 連接到 DB 了？_


- 整理所有 Blockchain Explorer 相關單子到這張[主任務單](https://github.com/CAFECA-IO/BAIFA/issues/495)，以方便前往參考其他相關單子。

- 因為不確定此單子要做的內容是什麼，因此先進去 Julian 的分支看看她前面做了什麼。
- 參考這個文件: src/pages/api/v1/app/chains/[chains_id]/blocks/index.ts
寫一段

- 記錄在此張 [PR - help wanted](https://github.com/CAFECA-IO/BAIFA/pull/497) 單子以便於 @Luphia & @Julian0701 可以 code review。

**Comment by Julian0701** [comment]
- take 2 hrs
- done

**Comment by Julian0701** [comment]
- take 1 hr

**Comment by Julian0701** [comment]
- take 1hr
