### ISSUE TITLE
Blockchain Explorer - 014 - Interactions from an address

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA#441]
API v1.1.0
https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0

014 - Interactions from an address
HTTP Request: GET /app/chains/:chain_id/addresses/:address_id/interactions?type=address

Parameters: type - required* (value: all(default) | address | contract)

Request Example:

GET /app/chains/isun/addresses/130294/interactions?type=address

Response Example:

[
  {
    "id": "122134",
    "type": "address",
    "chainId": "eth",
    "chainIcon": "/currencies/eth.svg",
    "publicTag": ["PUBLIC_TAG.UNKNOWN_USER"],
    "createdTimestamp": 167823123,
    "transactionCount": 2
  },
  {
    "id": "129381",
    "type": "address",
    "chainId": "eth",
    "chainIcon": "/currencies/eth.svg",
    "publicTag": ["PUBLIC_TAG.UNKNOWN_USER"],
    "createdTimestamp": 167538231,
    "transactionCount": 3
  },
  {
    "id": "322738",
    "type": "contract",
    "chainId": "eth",
    "chainIcon": "/currencies/eth.svg",
    "publicTag": ["PUBLIC_TAG.UNKNOWN_USER"],
    "createdTimestamp": 1678273194,
    "transactionCount": 2
  },
  {
    "id": "324472",
    "type": "contract",
    "chainId": "eth",
    "chainIcon": "/currencies/eth.svg",
    "publicTag": ["PUBLIC_TAG.UNKNOWN_USER"],
    "createdTimestamp": 1681310427,
    "transactionCount": 1
  }
  //...
]

**Comment by Julian0701** [comment]
- take 4 hrs
