### ISSUE TITLE
Blockchain Explorer - 015 - Get a contract data from a chain

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA#442]
API v1.1.0
https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0

015 - Get a contract data from a chain
HTTP Request: GET /app/chains/:chain_id/contracts/:contract_id

Parameters: none

Request Example: GET /app/chains/isun/contracts/330029

Response Example:

{
  "id": "330029",
  "type": "contract",
  "contractAddress": "0xA9D1e08C7793af67e9d92fe308d5697FB81d3E43",
  "chainId": "isun",
  "creatorAddressId": "130008",
  "createdTimestamp": 1688341795,
  "sourceCode": "",
  "transactionHistoryData": [
    {
      "id": "931314",
      "chainId": "isun",
      "createdTimestamp": 1607957394,
      "from": [
        { "type": "address", "address": "130008" }
        // FIXME:address like 0x356f9537631A773Ab9069fEc25f74Cd884132776
      ],
      "to": [
        { "type": "contract", "address": "330029" }
        // FIXME:address like 0x356f9537631A773Ab9069fEc25f74Cd884132776
      ],
      "type": "Evidence",
      "status": "SUCCESS"
    }
    //...
  ],
  "publicTag": ["PUBLIC_TAG.UNKNOWN_USER"]
}

**Comment by Julian0701** [comment]
- take 3 hrs
