### ISSUE TITLE
Blockchain Explorer - 016 - Get evidence data from a chain

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA#443]
API v1.1.0
https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0

016 - Get evidence data from a chain
HTTP Request: GET /app/chains/:chain_id/evidence/:evidence_id

Parameters: none

Request Example: GET /app/chains/btc/evidence/510071

Response Example:

{
  "id": "510071",
  "chainId": "btc",
  "evidenceAddress": "0x2326ce42a513a427a1ab5045a684e0a8ee8e96a13",
  "state": "Active",
  "creatorAddressId": "114007",
  "createdTimestamp": 1687103913,
  "content": "",
  "transactionHistoryData": [
    {
      "id": "915024",
      "chainId": "btc",
      "createdTimestamp": 1682817342,
      "from": [
        { "type": "address", "address": "114007" }
        // FIXME:address like 0x356f9537631A773Ab9069fEc25f74Cd884132776
      ],
      "to": [
        { "type": "contract", "address": "311382" }
        // FIXME:address like 0x356f9537631A773Ab9069fEc25f74Cd884132776
      ],
      "status": "SUCCESS"
    },
    {
      "id": "912299",
      "chainId": "btc",
      "createdTimestamp": 1684029313,
      "from": [
        { "type": "address", "address": "110132" }
        // FIXME:address like 0x356f9537631A773Ab9069fEc25f74Cd884132776
      ],
      "to": [
        { "type": "contract", "address": "310683" }
        // FIXME:address like 0x356f9537631A773Ab9069fEc25f74Cd884132776
      ],
      "status": "FAILED"
    }
    //...
  ]
}

**Comment by Julian0701** [comment]
- take 2.5 hrs
