### ISSUE TITLE
Blockchain Explorer - 018 - Get data from a currency

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA#445]
API v1.1.0
https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0

018 - Get data from a currency
HTTP Request: GET /app/currencies/:currency_id

Parameters: none

Request Example: GET /app/currencies/btc

Response Example:

{
  "currencyId": "btc",
  "currencyName": "Bitcoin",
  "rank": 1,
  "chainIcon": "/currencies/btc.svg",
  "holderCount": 324,
  "price": 27755.4,
  "volumeIn24h": 14867304472,
  "unit": "BTC",
  "totalAmount": 19388600,
  "holders": [
    {
      "addressId": "110029",
      "holdingAmount": 248597,
      "holdingPercentage": 1.28,
      "publicTag": ["PUBLIC_TAG.BINANCE_COLDWALLET"]
    },
    {
      "addressId": "110132",
      "holdingAmount": 178010,
      "holdingPercentage": 0.92,
      "publicTag": ["PUBLIC_TAG.BINANCE_COLDWALLET"]
    },
    {
      "addressId": "112840",
      "holdingAmount": 117351,
      "holdingPercentage": 0.61,
      "publicTag": ["PUBLIC_TAG.UNKNOWN_USER"]
    },
    {
      "addressId": "114007",
      "holdingAmount": 93109,
      "holdingPercentage": 0.48,
      "publicTag": ["PUBLIC_TAG.UNKNOWN_USER"]
    },
    {
      "addressId": "115588",
      "holdingAmount": 62352,
      "holdingPercentage": 0.32,
      "publicTag": ["PUBLIC_TAG.UNKNOWN_USER"]
    }
    // other holders
  ],
  "totalTransfers": 48010097,
  "flaggingCount": 24,
  "riskLevel": "HIGH_RISK",
  "transactionHistoryData": [
    {
      "id": "916841",
      "chainId": "btc",
      "createdTimestamp": 1679978987,
      "from": [{ "type": "address", "address": "115588" }], // FIXME:address like 0x356f9537631A773Ab9069fEc25f74Cd884132776
      "to": [{ "type": "contract", "address": "311382" }],
      "type": "Evidence",
      "status": "FAILED"
    },
    {
      "id": "914025",
      "chainId": "btc",
      "createdTimestamp": 1687909392,
      "from": [{ "type": "address", "address": "114007" }], // FIXME:address like 0x356f9537631A773Ab9069fEc25f74Cd884132776
      "to": [{ "type": "contract", "address": "311025" }],
      "type": "Crypto Currency",
      "status": "SUCCESS"
    }
    // ...other transaction history
  ]
}

**Comment by Julian0701** [comment]
- take 3 hrs, remain 2 hrs
- `holders`、`flaggingCount`、`transactionHistoryData` 需要討論

**Comment by Julian0701** [comment]
- take 2 hrs
- done
