### ISSUE TITLE
Blockchain Explorer - 020 - Get data from blacklist

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA#447]
API v1.1.0
https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0

020 - Get data from blacklist
HTTP Request: GET /app/blacklist

Parameters: none

Request Example: GET /app/blacklist

Response Example:

[
  {
    "id": "120008",
    "chainId": "eth",
    "latestActiveTime": 1686710310,
    "flaggingRecords": ["RED_FLAG_DETAIL_PAGE.FLAG_TYPE_HIGH_RISK_LOCATION"],
    "publicTag": ["PUBLIC_TAG.HACKER"]
  },
  {
    "id": "143281",
    "chainId": "usdt",
    "latestActiveTime": 1690283421,
    "flaggingRecords": ["RED_FLAG_DETAIL_PAGE.FLAG_TYPE_LARGE_WITHDRAW", "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_WITHDRAW"],
    "publicTag": ["PUBLIC_TAG.HACKER"]
  },
  {
    "id": "117263",
    "chainId": "btc",
    "latestActiveTime": 1682740134,
    "flaggingRecords": ["RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_TRANSFER", "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_RECEIVES"],
    "publicTag": ["PUBLIC_TAG.HACKER"]
  }
  // ...other blacklisted addresses
]

**Comment by Julian0701** [comment]
- take 1.5 hr
