### ISSUE TITLE
🧬 Connect API to database

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/BAIFA#495]
💡 小提示：請確認 API 規格文件 [API v1.1.0](https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0) 是否有更新，依照 API 規格文件為主。

---
- [x] #429 
- [x] #428 
- [x] #430 
- [x] #431
- [x] #432 
- [x] #433 
- [x] #434 
- [x] #435 
- [x] #436 
- [x] #437 
- [x] #438 
- [x] #439 
- [x] #440 
- [x] #441 
- [x] #442 
- [x] #443 
- [x] #444 
- [x] #445 
- [x] #446 
- [x] #447 
- [x] #448 
- [x] #449

**Comment by godmmt** [comment]
# 連線 TablePlus

- Download: 使用企業付費版本，從 Setapp 內下載。
- Settings:
  <img width="500" alt="截圖 2024-01-17 上午11 00 26" src="https://github.com/CAFECA-IO/BAIFA/assets/105651918/5c33a152-c5f2-447b-afdc-f9b28e2af7a5">

### Refs
- [Migration & Table Plus 工具 (2)](https://ithelp.ithome.com.tw/articles/10327151)
- [TablePlus Document](https://docs.tableplus.com/)
- [Toolbar](https://docs.tableplus.com/gui-tools/the-interface/toolbar)

**Comment by godmmt** [comment]
@godmmt : 

- #440 
- #446 
- #448 
- #449

**Comment by godmmt** [comment]
### 參考 DB 文件：https://github.com/CAFECA-IO/Documents/tree/main/BFA/db_schema

**Comment by godmmt** [comment]
@Julian0701 可以用這個表格檢查是否已刪掉 pg : 
---
- [ ] #428 
- [ ] #429 
- [ ] #430 
- [ ] #431
- [ ] #432 
- [ ] #433 
- [ ] #434 
- [ ] #435 
- [ ] #436 
- [ ] #437 
- [ ] #438 
- [ ] #439 
- [ ] #440 
- [ ] #441 
- [ ] #442 
- [ ] #443 
- [ ] #444 
- [ ] #445 
- [ ] #446 
- [ ] #447 
- [ ] #448 
- [ ] #449

**Comment by godmmt** [comment]
took 1 hour for planning

**Comment by godmmt** [comment]
## 參考 DB 文件：https://github.com/CAFECA-IO/Documents/tree/main/BFA/db_schema

**Comment by godmmt** [comment]
took 1 hour for planning

**Comment by Julian0701** [comment]
013 - Get red flags data from an Address
019 - Get red flags data from a currency
021 - Get all red flags data / Get red flags data from a currency, chain, or address
- 移除 `addressId`
----------
022 - Get data from a red flag
- 移除 `addressId`、`address`

**Comment by godmmt** [comment]
- [x] API 文件修改
