### ISSUE TITLE
[UX] BAIFA 2.0 - 區塊鏈鑑識 User flow 

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/BAIFA#515]
依據 區塊鏈鑑識 Function Map 建立 User flow

**Comment by JodieWu** [comment]
完成時間： 4 hr

[特殊身份人員註冊流程](https://www.figma.com/file/e7VJr5kgdJ0fp4HSGZqt8t/BAIFA-2.0?type=whiteboard&node-id=16-9317&t=pZGoBQsSOubq5DGF-4)

[一般用戶訂閱服務](https://www.figma.com/file/e7VJr5kgdJ0fp4HSGZqt8t/BAIFA-2.0?type=whiteboard&node-id=16-10457&t=pZGoBQsSOubq5DGF-4)

[追蹤名單設定流程](https://www.figma.com/file/e7VJr5kgdJ0fp4HSGZqt8t/BAIFA-2.0?type=whiteboard&node-id=16-10868&t=pZGoBQsSOubq5DGF-4)

[Address Review 流程](https://www.figma.com/file/e7VJr5kgdJ0fp4HSGZqt8t/BAIFA-2.0?type=whiteboard&node-id=16-12336&t=pZGoBQsSOubq5DGF-4)

[Tracking Tool 使用流程](https://www.figma.com/file/e7VJr5kgdJ0fp4HSGZqt8t/BAIFA-2.0?type=whiteboard&node-id=16-13582&t=pZGoBQsSOubq5DGF-4)
