### ISSUE TITLE
TransactionSearch

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#52]
[Mockup](https://www.figma.com/proto/gC4On1ULcel7UzXMwdS9cY/BAIFAAA?type=design&node-id=307-27506&scaling=scale-down&page-id=46%3A771&starting-point-node-id=46%3A772)

![截圖 2023-06-19 上午11 57 54](https://github.com/CAFECA-IO/boltchain.io/assets/114177573/66306d1d-eee4-4d59-a6a3-b8cc54024a35)

**Comment by Julian0701** [comment]
與 Block tab 的 `SearchFilter` 通用

**Comment by Luphia** [comment]
- deprecated mission
