### ISSUE TITLE
BlackListSearch

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#65]
[Mockup](https://www.figma.com/proto/gC4On1ULcel7UzXMwdS9cY/BAIFAAA?type=design&node-id=307-26820&scaling=scale-down&page-id=46%3A771&starting-point-node-id=46%3A772)

![截圖 2023-06-19 下午12 06 50](https://github.com/CAFECA-IO/boltchain.io/assets/114177573/9e8294f7-4a07-4306-a8a8-81db49d7dbc0)

**Comment by Julian0701** [comment]
與 Block tab 的 `SearchFilter` 通用

**Comment by Luphia** [comment]
- deprecated mission
