### ISSUE TITLE
Opening detailed address page from crypto won't get the chain icon

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/BAIFA#675]
- 從 crypto 頁面點進 address detail page ，會拿不到 chain icon

![image](https://github.com/CAFECA-IO/BAIFA/assets/20677913/f705db72-f647-44b6-99fa-30ed8578b1f1)

**Comment by godmmt** [comment]
![](https://github.com/CAFECA-IO/BAIFA/assets/105651918/2b611fc2-6fe3-4bc9-b279-75839193aeca)

**Comment by godmmt** [comment]
原先傳的 chain id 是 0x0000000000000000000000000000000000000000
要改成傳過去的參數是 8017

**Comment by godmmt** [comment]
![](https://github.com/CAFECA-IO/BAIFA/assets/105651918/d1ddd7e3-432f-4a4a-90fd-f3b5684aaa5f)
![](https://github.com/CAFECA-IO/BAIFA/assets/105651918/3d5e0c74-6201-4fc8-9ae9-8d6488644fe3)

**Comment by godmmt** [comment]
took 1 hour

done
