### ISSUE TITLE
[Document] 交易事件抽樣報告 Template

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/BAIFA#678]
交易事件抽樣報告內容及樣式設計

**Comment by StrawHo** [comment]
LINK:https://www.figma.com/file/XK4nokzjXRv3g4TOFmEPpj/BAIFA-Report?type=design&node-id=65%3A569&mode=design&t=wytmRgL14RzedBsh-1

參考資料：
[抽樣報告交易事件.pdf](https://github.com/CAFECA-IO/BAIFA/files/14442566/default.pdf)

花費時間：約5hr
