### ISSUE TITLE
review_datas schema 需要修改

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/BAIFA#705]
因為 target 不可能同時是 address 跟 transactions，加上會有多筆 review 的 target 是一樣的，所以需要修改 review_datas schema
- [x] 取消 target `@unique`
- [x] 刪掉 addresses relation
- [x] 刪掉 transactions relation

**Comment by gibbs-shih** [comment]
- 更新文件 [DB Schema: review_datas](https://github.com/CAFECA-IO/Documents/blob/main/BFA/db_schema/review_datas.md) 
- 更新文件 [BFAER00002](https://github.com/CAFECA-IO/Documents/blob/main/BFA/BFAER00002.md)
- 修改 db shema ：`review_datas`
![CleanShot 2024-02-21 at 11 44 19](https://github.com/CAFECA-IO/BAIFA-web-crawling/assets/73210852/f39b1e04-ffc0-49f8-885b-a43577e0d3d6)
![CleanShot 2024-02-21 at 11 51 10](https://github.com/CAFECA-IO/BAIFA-web-crawling/assets/73210852/a1c69e76-cb47-4c89-b988-d4c00938c272)
![CleanShot 2024-02-21 at 11 51 57](https://github.com/CAFECA-IO/BAIFA-web-crawling/assets/73210852/f6334f35-1e44-4f66-9ee4-9a58a4c6881b)

- 更新資料庫
<img width="813" alt="CleanShot 2024-02-21 at 12 08 13@2x" src="https://github.com/CAFECA-IO/BAIFA-web-crawling/assets/73210852/cd1fcb4b-5c09-49b3-af8f-6ca05e99e135">

**Comment by gibbs-shih** [comment]
take about 1 hr
