### ISSUE TITLE
拆分 API - 018

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#730]
將 [API 018](https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0#018---get-data-from-a-currency) 中的 `holders` 和 `transactionHistoryData` 拆分出來，另外寫成新的 API

- [x] 新增 API
- [x] 調整 API 文件

**Comment by godmmt** [comment]
# 已於下面工作單完成

- https://github.com/CAFECA-IO/BAIFA/issues/790
- https://github.com/CAFECA-IO/BAIFA/issues/852
