### ISSUE TITLE
［User research]易用性測試前置準備

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/BAIFA#754]
- [x] 任務設計
- [x] 事後問卷
- [x] 資料搜集問卷
- [x] 測試評估表格製作
- [x] SUS量表

@StrawHo - 1 pt
@JodieWu - 4 pts

**Comment by JodieWu** [comment]
# 任務

Task goal：
提供 20 張 1-2月份發票，請受試者完成營業稅申報

Scenario:
假設你今天是一間會計師事務所的會計師，您手上有一間需要您協助處理外帳的公司，你收到了該公司寄過來的1-2月份憑證，需要你協助完成營業稅申報。

-------

Task goal：

提供 10 張 2月份發票及10張銷貨單，請受試者完成報表生成

Scenario:
假設你今天是一間會計師事務所的會計師，您手上有一間需要您協助處理內帳的公司，你收到了該公司寄過來的2月份憑證及銷貨單，需要你提供上個月份的財務報表。

-------

**Comment by JodieWu** [comment]
完成時間： 5 hr

[測試評估表格 .pdf](https://github.com/CAFECA-IO/BAIFA/files/14443819/default.pdf)
[易用性測試-事後問卷 .pdf](https://github.com/CAFECA-IO/BAIFA/files/14443821/-.pdf)

**Comment by StrawHo** [comment]
[測試資料紀錄表.pdf](https://github.com/CAFECA-IO/BAIFA/files/14444024/default.pdf)
