### ISSUE TITLE
truncate text by tailwind css

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/BAIFA#793]
- 查詢之後發現可以用 tailwind css + vanilla css 依照畫面寬度截斷文字，做法如 ref，所以可以優化有使用 truncateText 的 component
- ref
    - https://tailwindcss.com/docs/text-overflow
    - https://stackoverflow.com/questions/21861125/set-dot-color-of-text-overflow-ellipsis
    
<img width="822" alt="image" src="https://github.com/CAFECA-IO/BAIFA/assets/20677913/d301c075-2792-47bd-b422-919eb46eb359">

**Comment by Julian0701** [comment]
- take 4 hrs, remain 2 hrs

**Comment by Julian0701** [comment]
- take 5 hrs
