### ISSUE TITLE
Refactor pagination functionality on the page of interaction of address/contract

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/BAIFA#796]
重構 `/[addressId]/interactions` 頁面，透過 API 參數拿資料
- [x] date
- [x] sorting
- [x] pagination
- [x] input search
- [x] type
- [x] 修改 API 文件

**Comment by Julian0701** [comment]
- take 5 hrs, remain 2 hrs
- sorting 尚未完成

**Comment by Julian0701** [comment]
- take 2 hrs
