### ISSUE TITLE
[Wireframe] BAIFA 2.0 會計插件-會計插件之一鍵節稅

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/BAIFA#801]
參考資訊
![image](https://github.com/CAFECA-IO/BAIFA/assets/77717533/285aace3-cb6d-4def-9167-af2b09669bfb)

**Comment by JodieWu** [comment]
完成時間： 4 hr

https://www.figma.com/file/XHculXs7KVxt9GDSEXJhBv/BAIFA-2.0?type=design&node-id=358%3A136541&mode=design&t=Exd6uCkRB0HKzZPc-1
