### ISSUE TITLE
區塊瀏覽畫面顯示礦工資訊

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/BAIFA#841]
- [x] 區塊瀏覽畫面顯示礦工資訊
- [x] 調整 API 文件
- [x] 手機介面換行問題

---

相關資訊：
- API : [006](https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.1#006---get-all-blocks-data-from-a-chain--get-period-blocks-data-from-a-chain)
- 畫面 : https://baifa.io/en/app/chains/8017

**Comment by godmmt** [comment]
手機換行問題：
![截圖 2024-03-11 上午11 26 29](https://github.com/CAFECA-IO/BAIFA/assets/105651918/0473c3ed-ea95-462f-b1b9-aac0bca4b106)

**Comment by Julian0701** [comment]
- take 3 hrs
