### ISSUE TITLE
將 getStaticPaths & getStaticProps 改成 getServerSideProps

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#857]
[參考做法](https://github.com/CAFECA-IO/BAIFA/issues/795#issuecomment-1976107123)

- [x]  探索區塊鏈`/app/chains` *API 004*
- [x]  區塊鏈詳細 `/app/chains/[chainId]` *API 005*
    - [x]  Block tab *API 006*
    - [x]  Transaction tab *API 009*
- [x]  區塊詳細 `/app/chains/[chainId]/block/[blockId]` *API 007*
- [x]  區塊下的交易列表 `/app/chains/[chainId]/block/[blockId]/transactions` *API 008*
- [x]  交易詳細`/app/chains/[chainId]/transaction/[transactionId]` *API 010*
- [x]  合約詳細 `/app/chains/[chainId]/contract/[contractId]` *API 015*
- [x]  證據詳細 `/app/chains/[chainId]/evidence/[evidenceId]` *API 016*
- [x]  地址間的交易歷史列表 `/app/chains/[chainId]/transactions` *API 009*

**Comment by arealclimber** [comment]
taking 3 hrs
