### ISSUE TITLE
將排序 query 改成 desc/asc

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#858]
不要用 i18n code，改用 TimeSortingType
檢查 8 個 API / 頁面
- 探索區塊鏈`/app/chains` *API 004*
- 區塊鏈詳細 `/app/chains/[chainId]` *API 005*
    - [x]  Block tab *API 006*
    - [x]  Transaction tab *API 009*
- 區塊詳細 `/app/chains/[chainId]/block/[blockId]` *API 007*
- [x]  區塊下的交易列表 `/app/chains/[chainId]/block/[blockId]/transactions` *API 008*
- 交易詳細`/app/chains/[chainId]/transaction/[transactionId]` *API 010*
- 合約詳細 `/app/chains/[chainId]/contract/[contractId]` *API 015*
- 證據詳細 `/app/chains/[chainId]/evidence/[evidenceId]` *API 016*
- [x]  地址間的交易歷史列表 `/app/chains/[chainId]/transactions` *API 009*

**Comment by arealclimber** [comment]
taking 1 hr
- 修改 API 的邏輯

remaining 1 hr
- 修改 UI 傳入 API query

**Comment by arealclimber** [comment]
taking 0.5 hrs
- solved by https://github.com/CAFECA-IO/BAIFA/pull/907
