### ISSUE TITLE
token balances DB ＆ crawler 調整

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/BAIFA#859]
DB 的 token_balances 的 value 欄位因為要排序，所以要補齊 64 位（從前面開始補0）。並且要加索引。

**Comment by gibbs-shih** [comment]
- 添加索引
![CleanShot 2024-03-13 at 10 53 33](https://github.com/CAFECA-IO/BAIFA/assets/73210852/0b319d05-eda4-4c5a-aaa0-ebfb0d1b4aca)
![CleanShot 2024-03-13 at 10 59 44](https://github.com/CAFECA-IO/BAIFA/assets/73210852/d9a14ce0-da85-418e-8e38-a7514c14176a)

- 補零 function
![CleanShot 2024-03-13 at 14 13 33](https://github.com/CAFECA-IO/BAIFA/assets/73210852/cfeaa7ca-fc84-4f36-a3b6-f7a4a99b0cd1)

- 更新 updateTokenBalances
![CleanShot 2024-03-13 at 14 15 15](https://github.com/CAFECA-IO/BAIFA/assets/73210852/6ec024c1-f89d-4de3-ae79-8072b36443c6)
![CleanShot 2024-03-13 at 14 16 08](https://github.com/CAFECA-IO/BAIFA/assets/73210852/607c6797-c816-44d3-962e-3bf29602de6a)

- 更新 toTokenBalances
![CleanShot 2024-03-13 at 14 28 13](https://github.com/CAFECA-IO/BAIFA/assets/73210852/bead77b7-ebdd-48d8-b16b-8a31a14a72cd)
![CleanShot 2024-03-13 at 14 29 39](https://github.com/CAFECA-IO/BAIFA/assets/73210852/7ec4a1db-ffde-4cdc-8e12-5a86b26b147b)

- 測試
![CleanShot 2024-03-13 at 17 38 50](https://github.com/CAFECA-IO/BAIFA/assets/73210852/fe1abb96-de11-4742-89b0-8e832dd81ba4)

**Comment by gibbs-shih** [comment]
take 4 hr
