### ISSUE TITLE
codes table 跟文件不一致 (transactions type)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/BAIFA#894]
根據 [doc](https://github.com/CAFECA-IO/Documents/blob/main/BFA/db_schema/codes.md) 跟 transactions table，type 99 代表 Others ，但 codes table 上沒有紀錄 transaction type 99 對應 Others

e.g. transaction hash: `0xb3d31117ff3c3c4cb5d33aab9b8fd8d98ace4f4ba2ee9100d1b67e0ecaf0f1ed`
<img width="1219" alt="image" src="https://github.com/CAFECA-IO/BAIFA/assets/20677913/d80838c3-d457-463a-81ce-3a4a29f37ff4">

<img width="440" alt="Screenshot 2024-03-13 at 16 33 23" src="https://github.com/CAFECA-IO/BAIFA/assets/20677913/7698a2e1-160d-4804-a407-cc4bf316be54">

**Comment by gibbs-shih** [comment]
- 修改文件, schema
![CleanShot 2024-03-14 at 14 16 56](https://github.com/CAFECA-IO/BAIFA/assets/73210852/44397fbf-d4b1-45dd-b5b9-fe595a891eec)
![CleanShot 2024-03-14 at 14 19 45](https://github.com/CAFECA-IO/BAIFA/assets/73210852/6b5bb4ca-df09-4879-b2fe-df0bb331431f)
![CleanShot 2024-03-14 at 14 28 58](https://github.com/CAFECA-IO/BAIFA/assets/73210852/10cf9672-c3fa-4acc-9f89-8f3b7103002e)

**Comment by gibbs-shih** [comment]
take 1 hr
