### ISSUE TITLE
miner 需要被紀錄在 addresses table 上

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/BAIFA#895]
- miner 需要被紀錄在 addresses table 上，才能對應顯示此 address 的相關資料，否則會查無地址資料，但是卻有 block produced history e.g. https://baifa.io/en/app/chains/8017/address/0x1f6f37e92ac9ed2292144d0a12e6d8f9b0d2d25b

![image](https://github.com/CAFECA-IO/BAIFA/assets/20677913/84107046-d469-4b12-b30c-5156c8052bad)

**Comment by gibbs-shih** [comment]
- 新增 parseBlockMinerAddress function 來記錄 miner address
- 並更新 created timestamp 及 latest active time
![CleanShot 2024-03-22 at 13 35 40](https://github.com/CAFECA-IO/BAIFA/assets/73210852/96e1c565-2614-46ea-9e7c-451557fd8645)

**Comment by gibbs-shih** [comment]
- 在解析完 block 後解析 miner address
![CleanShot 2024-03-22 at 14 27 04](https://github.com/CAFECA-IO/BAIFA/assets/73210852/753945cd-99c8-4c89-90db-45933c505783)

**Comment by gibbs-shih** [comment]
- address table
![CleanShot 2024-03-22 at 14 46 52@2x](https://github.com/CAFECA-IO/BAIFA/assets/73210852/251ae0a8-c683-4b00-959a-b977a4b918e2)

**Comment by gibbs-shih** [comment]
take 5 hr
